/**
 * MUAP-only tokens — transcribed from docs/designs/muap-v2-tokenization.md rev 2.4.
 */
import type { TemplateToken } from './types'

export const MUAP_ONLY_TOKENS: ReadonlyArray<TemplateToken> = [
  // --- MUAP T2-T6 existing ---
  { name: 'no_muap', templates: ['muap'], kind: 'fact-display', source: 'app', description: 'no muap', anchor: 'MUAP T2-T6 existing' },
  { name: 'tanggal', templates: ['muap'], kind: 'fact-display', source: 'app', description: 'tanggal', anchor: 'MUAP T2-T6 existing' },
  { name: 'unit_pengelola', templates: ['muap'], kind: 'fact-display', source: 'app', description: 'unit pengelola', anchor: 'MUAP T2-T6 existing' },
  { name: 'nama_perusahaan_or_inisial', templates: ['muap'], kind: 'categorical', source: 'app', description: 'nama perusahaan or inisial', anchor: 'MUAP T2-T6 existing', enum: ['Ya', 'Tidak'] },
  { name: 'nama_jabatan_direktur', templates: ['muap'], kind: 'fact-display', source: 'app', description: 'nama jabatan direktur', anchor: 'MUAP T2-T6 existing' },
  { name: 'nama_jabatan_komisaris', templates: ['muap'], kind: 'fact-display', source: 'app', description: 'nama jabatan komisaris', anchor: 'MUAP T2-T6 existing' },
  { name: 'nomor_surat_permohonan', templates: ['muap'], kind: 'fact-display', source: 'app', description: 'nomor surat permohonan', anchor: 'MUAP T2-T6 existing' },
  { name: 'tanggal_surat_permohonan', templates: ['muap'], kind: 'fact-display', source: 'app', description: 'tanggal surat permohonan', anchor: 'MUAP T2-T6 existing' },
  { name: 'tujuan', templates: ['muap'], kind: 'fact-display', source: 'app', description: 'tujuan', anchor: 'MUAP T2-T6 existing' },
  { name: 'tenor_in_bulan', templates: ['muap'], kind: 'fact-display', source: 'app', description: 'tenor in bulan', anchor: 'MUAP T2-T6 existing' },
  // --- MUAP T7 existing ---
  { name: 'modal_kerja_or_investasi_1', templates: ['muap'], kind: 'categorical', source: 'app', description: 'modal kerja or investasi 1', anchor: 'MUAP T7 existing', enum: ['Modal Kerja', 'Investasi'] },
  { name: 'akad_1', templates: ['muap'], kind: 'fact-display', source: 'app', description: 'akad 1', anchor: 'MUAP T7 existing' },
  { name: 'outstanding_balance_berjalan_1', templates: ['muap'], kind: 'fact-display', source: 'app', description: 'outstanding balance berjalan 1', anchor: 'MUAP T7 existing' },
  { name: 'topup_1', templates: ['muap'], kind: 'fact-display', source: 'app', description: 'topup 1', anchor: 'MUAP T7 existing' },
  { name: 'topup_max_1', templates: ['muap'], kind: 'fact-display', source: 'app', description: 'topup max 1', anchor: 'MUAP T7 existing' },
  { name: 'keterangan_1', templates: ['muap'], kind: 'fact-display', source: 'app', description: 'keterangan 1', anchor: 'MUAP T7 existing' },
  { name: 'modal_kerja_or_investasi_2', templates: ['muap'], kind: 'categorical', source: 'app', description: 'modal kerja or investasi 2', anchor: 'MUAP T7 existing', enum: ['Modal Kerja', 'Investasi'] },
  { name: 'akad_2', templates: ['muap'], kind: 'fact-display', source: 'app', description: 'akad 2', anchor: 'MUAP T7 existing' },
  { name: 'outstanding_balance_berjalan_2', templates: ['muap'], kind: 'fact-display', source: 'app', description: 'outstanding balance berjalan 2', anchor: 'MUAP T7 existing' },
  { name: 'topup_2', templates: ['muap'], kind: 'fact-display', source: 'app', description: 'topup 2', anchor: 'MUAP T7 existing' },
  { name: 'topup_max_2', templates: ['muap'], kind: 'fact-display', source: 'app', description: 'topup max 2', anchor: 'MUAP T7 existing' },
  { name: 'keterangan_2', templates: ['muap'], kind: 'fact-display', source: 'app', description: 'keterangan 2', anchor: 'MUAP T7 existing' },
  // --- MUAP T11-T18 existing ---
  { name: 'total_outstanding_balance', templates: ['muap'], kind: 'fact-calc', source: 'derived', description: 'total outstanding balance', anchor: 'MUAP T11-T18 existing', formula: 'Calculated from related template values at fill time' },
  { name: 'total_topup', templates: ['muap'], kind: 'fact-calc', source: 'derived', description: 'total topup', anchor: 'MUAP T11-T18 existing', formula: 'Calculated from related template values at fill time' },
  { name: 'total_topup_max', templates: ['muap'], kind: 'fact-calc', source: 'derived', description: 'total topup max', anchor: 'MUAP T11-T18 existing', formula: 'Calculated from related template values at fill time' },
  { name: 'alamat_perusahaan_sesuai_legal', templates: ['muap'], kind: 'fact-display', source: 'app', description: 'alamat perusahaan sesuai legal', anchor: 'MUAP T11-T18 existing' },
  { name: 'ahu_akta_pendirian', templates: ['muap'], kind: 'fact-display', source: 'app', description: 'ahu akta pendirian', anchor: 'MUAP T11-T18 existing' },
  { name: 'no_akta_perubahan', templates: ['muap'], kind: 'fact-display', source: 'app', description: 'no akta perubahan', anchor: 'MUAP T11-T18 existing' },
  { name: 'tanggal_akta_perubahan', templates: ['muap'], kind: 'fact-display', source: 'app', description: 'tanggal akta perubahan', anchor: 'MUAP T11-T18 existing' },
  { name: 'keterangan_perubahan', templates: ['muap'], kind: 'fact-display', source: 'app', description: 'keterangan perubahan', anchor: 'MUAP T11-T18 existing' },
  { name: 'tanggal_nib', templates: ['muap'], kind: 'fact-display', source: 'app', description: 'tanggal nib', anchor: 'MUAP T11-T18 existing' },
  { name: 'sesuai_or_tidak_dengan_riil', templates: ['muap'], kind: 'categorical', source: 'app', description: 'sesuai or tidak dengan riil', anchor: 'MUAP T11-T18 existing', enum: ['Sesuai', 'Tidak Sesuai'] },
  { name: 'lembar_saham_direktur', templates: ['muap'], kind: 'fact-display', source: 'app', description: 'lembar saham direktur', anchor: 'MUAP T11-T18 existing' },
  { name: 'nilai_saham_direktur', templates: ['muap'], kind: 'fact-display', source: 'app', description: 'nilai saham direktur', anchor: 'MUAP T11-T18 existing' },
  { name: 'lembar_saham_komisaris', templates: ['muap'], kind: 'fact-display', source: 'app', description: 'lembar saham komisaris', anchor: 'MUAP T11-T18 existing' },
  { name: 'nilai_saham_komisaris', templates: ['muap'], kind: 'fact-display', source: 'app', description: 'nilai saham komisaris', anchor: 'MUAP T11-T18 existing' },
  { name: 'total_lembar_saham', templates: ['muap'], kind: 'fact-calc', source: 'derived', description: 'total lembar saham', anchor: 'MUAP T11-T18 existing', formula: 'Calculated from related template values at fill time' },
  { name: 'total_nilai_saham', templates: ['muap'], kind: 'fact-calc', source: 'derived', description: 'total nilai saham', anchor: 'MUAP T11-T18 existing', formula: 'Calculated from related template values at fill time' },
  { name: 'nama_lengkap_non_formal', templates: ['muap'], kind: 'fact-display', source: 'app', description: 'nama lengkap non formal', anchor: 'MUAP T11-T18 existing' },
  { name: 'ai_keterangan_key_person_non_formal', templates: ['muap'], kind: 'narrative-ai', source: 'ai-with-research-context', description: 'ai keterangan key person non formal', anchor: 'MUAP T11-T18 existing' },
  { name: 'tanggal_slik_ojk', templates: ['muap'], kind: 'fact-display', source: 'app', description: 'tanggal slik ojk', anchor: 'MUAP T11-T18 existing' },
  { name: 'tanggal_data_terakhir', templates: ['muap'], kind: 'fact-display', source: 'app', description: 'tanggal data terakhir', anchor: 'MUAP T11-T18 existing' },
  { name: 'ai_keterangan_tujuan_pembiayaan', templates: ['muap'], kind: 'narrative-ai', source: 'ai-with-research-context', description: 'ai keterangan tujuan pembiayaan', anchor: 'MUAP T11-T18 existing' },
  { name: 'ai_kesimpulan_analisis_yuridis', templates: ['muap'], kind: 'narrative-ai', source: 'ai-with-research-context', description: 'ai kesimpulan analisis yuridis', anchor: 'MUAP T11-T18 existing' },
  { name: 'ai_profil_perusahaan', templates: ['muap'], kind: 'narrative-ai', source: 'ai-with-research-context', description: 'ai profil perusahaan', anchor: 'MUAP T11-T18 existing' },
  // --- MUAP post-T21/pre-T25 ---
  { name: 'ai_pefindo_narrative', templates: ['muap'], kind: 'narrative-ai', source: 'ai-with-research-context', description: 'ai pefindo narrative', anchor: 'MUAP post-T21/pre-T25' },
  { name: 'ai_industri_overview', templates: ['muap'], kind: 'narrative-ai', source: 'ai-with-research-context', description: 'ai industri overview', anchor: 'MUAP post-T21/pre-T25' },
  // --- MUAP T25 — Analisis Industri ---
  { name: 'tren_industri_or_stagnan', templates: ['muap'], kind: 'categorical', source: 'app', description: 'tren industri or stagnan', anchor: 'MUAP T25 — Analisis Industri', enum: ['Positif', 'Stagnan', 'Negatif'] },
  { name: 'ai_tren_industri_penjelasan', templates: ['muap'], kind: 'narrative-ai', source: 'ai-with-research-context', description: 'ai tren industri penjelasan', anchor: 'MUAP T25 — Analisis Industri' },
  { name: 'ai_pemain_utama', templates: ['muap'], kind: 'narrative-ai', source: 'ai-with-research-context', description: 'ai pemain utama', anchor: 'MUAP T25 — Analisis Industri' },
  { name: 'barrier_to_entry', templates: ['muap'], kind: 'categorical', source: 'app', description: 'barrier to entry', anchor: 'MUAP T25 — Analisis Industri', enum: ['Tinggi', 'Sedang', 'Rendah'] },
  { name: 'ai_barrier_to_entry_penjelasan', templates: ['muap'], kind: 'narrative-ai', source: 'ai-with-research-context', description: 'ai barrier to entry penjelasan', anchor: 'MUAP T25 — Analisis Industri' },
  { name: 'regulasi_perubahan_or_tidak', templates: ['muap'], kind: 'categorical', source: 'app', description: 'regulasi perubahan or tidak', anchor: 'MUAP T25 — Analisis Industri', enum: ['Ya', 'Tidak'] },
  { name: 'ai_regulasi_perubahan_penjelasan', templates: ['muap'], kind: 'narrative-ai', source: 'ai-with-research-context', description: 'ai regulasi perubahan penjelasan', anchor: 'MUAP T25 — Analisis Industri' },
  { name: 'disrupsi_teknologi_or_tidak', templates: ['muap'], kind: 'categorical', source: 'app', description: 'disrupsi teknologi or tidak', anchor: 'MUAP T25 — Analisis Industri', enum: ['Ya', 'Tidak'] },
  { name: 'ai_disrupsi_teknologi_penjelasan', templates: ['muap'], kind: 'narrative-ai', source: 'ai-with-research-context', description: 'ai disrupsi teknologi penjelasan', anchor: 'MUAP T25 — Analisis Industri' },
  { name: 'musiman_or_tidak', templates: ['muap'], kind: 'categorical', source: 'app', description: 'musiman or tidak', anchor: 'MUAP T25 — Analisis Industri', enum: ['Ya', 'Tidak'] },
  { name: 'ai_musiman_penjelasan', templates: ['muap'], kind: 'narrative-ai', source: 'ai-with-research-context', description: 'ai musiman penjelasan', anchor: 'MUAP T25 — Analisis Industri' },
  { name: 'ai_faktor_makro', templates: ['muap'], kind: 'narrative-ai', source: 'ai-with-research-context', description: 'ai faktor makro', anchor: 'MUAP T25 — Analisis Industri' },
  { name: 'ai_fatwa_dsn_mui_risk', templates: ['muap'], kind: 'narrative-ai', source: 'ai-with-research-context', description: 'ai fatwa dsn mui risk', anchor: 'MUAP T25 — Analisis Industri' },
  { name: 'ai_industri_peluang_tantangan', templates: ['muap'], kind: 'narrative-ai', source: 'ai-with-research-context', description: 'ai industri peluang tantangan', anchor: 'MUAP T25 — Analisis Industri' },
  // --- MUAP T29 — Lokasi & Visit ---
  { name: 'status_tempat_usaha', templates: ['muap'], kind: 'categorical', source: 'app', description: 'status tempat usaha', anchor: 'MUAP T29 — Lokasi & Visit', enum: ['Milik Sendiri', 'Sewa', 'Pinjam Pakai'] },
  { name: 'status_tempat_usaha_berlaku_sampai', templates: ['muap'], kind: 'categorical', source: 'app', description: 'status tempat usaha berlaku sampai', anchor: 'MUAP T29 — Lokasi & Visit', enum: ['Ya', 'Tidak'] },
  { name: 'kondisi_tempat_usaha', templates: ['muap'], kind: 'categorical', source: 'app', description: 'kondisi tempat usaha', anchor: 'MUAP T29 — Lokasi & Visit', enum: ['Representatif', 'Cukup', 'Kurang'] },
  { name: 'ai_kondisi_tempat_usaha_deskripsi', templates: ['muap'], kind: 'narrative-ai', source: 'ai-with-research-context', description: 'ai kondisi tempat usaha deskripsi', anchor: 'MUAP T29 — Lokasi & Visit' },
  { name: 'konsistensi_lokasi_skala_or_tidak', templates: ['muap'], kind: 'categorical', source: 'app', description: 'konsistensi lokasi skala or tidak', anchor: 'MUAP T29 — Lokasi & Visit', enum: ['Sesuai', 'Tidak Sesuai'] },
  { name: 'ai_konsistensi_lokasi_skala_penjelasan', templates: ['muap'], kind: 'narrative-ai', source: 'ai-with-research-context', description: 'ai konsistensi lokasi skala penjelasan', anchor: 'MUAP T29 — Lokasi & Visit' },
  // --- MUAP T31 — Aktivitas Operasional ---
  { name: 'aktivitas_hari_1', templates: ['muap'], kind: 'fact-display', source: 'app', description: 'aktivitas hari 1', anchor: 'MUAP T31 — Aktivitas Operasional' },
  { name: 'aktivitas_hari_2', templates: ['muap'], kind: 'fact-display', source: 'app', description: 'aktivitas hari 2', anchor: 'MUAP T31 — Aktivitas Operasional' },
  { name: 'aktivitas_hari_3', templates: ['muap'], kind: 'fact-display', source: 'app', description: 'aktivitas hari 3', anchor: 'MUAP T31 — Aktivitas Operasional' },
  { name: 'aktivitas_hari_4', templates: ['muap'], kind: 'fact-display', source: 'app', description: 'aktivitas hari 4', anchor: 'MUAP T31 — Aktivitas Operasional' },
  { name: 'aktivitas_hari_5', templates: ['muap'], kind: 'fact-display', source: 'app', description: 'aktivitas hari 5', anchor: 'MUAP T31 — Aktivitas Operasional' },
  { name: 'ai_produk_jasa_proses_bisnis', templates: ['muap'], kind: 'narrative-ai', source: 'ai-with-research-context', description: 'ai produk jasa proses bisnis', anchor: 'MUAP T31 — Aktivitas Operasional' },
  // --- MUAP T34 — Pelanggan Utama ---
  { name: 'nama_pelanggan_1', templates: ['muap'], kind: 'fact-display', source: 'app', description: 'nama pelanggan 1', anchor: 'MUAP T34 — Pelanggan Utama' },
  { name: 'kota_pelanggan_1', templates: ['muap'], kind: 'fact-display', source: 'app', description: 'kota pelanggan 1', anchor: 'MUAP T34 — Pelanggan Utama' },
  { name: 'lama_relasi_pelanggan_1_tahun', templates: ['muap'], kind: 'fact-display', source: 'app', description: 'lama relasi pelanggan 1 tahun', anchor: 'MUAP T34 — Pelanggan Utama' },
  { name: 'nilai_bulanan_pelanggan_1', templates: ['muap'], kind: 'fact-display', source: 'app', description: 'nilai bulanan pelanggan 1', anchor: 'MUAP T34 — Pelanggan Utama' },
  { name: 'metode_pelanggan_1', templates: ['muap'], kind: 'fact-display', source: 'app', description: 'metode pelanggan 1 (free-text: cara checking dilakukan)', anchor: 'MUAP T34 — Pelanggan Utama' },
  { name: 'tanggal_pelanggan_1', templates: ['muap'], kind: 'fact-display', source: 'app', description: 'tanggal pelanggan 1', anchor: 'MUAP T34 — Pelanggan Utama' },
  { name: 'nama_pelanggan_2', templates: ['muap'], kind: 'fact-display', source: 'app', description: 'nama pelanggan 2', anchor: 'MUAP T34 — Pelanggan Utama' },
  { name: 'kota_pelanggan_2', templates: ['muap'], kind: 'fact-display', source: 'app', description: 'kota pelanggan 2', anchor: 'MUAP T34 — Pelanggan Utama' },
  { name: 'lama_relasi_pelanggan_2_tahun', templates: ['muap'], kind: 'fact-display', source: 'app', description: 'lama relasi pelanggan 2 tahun', anchor: 'MUAP T34 — Pelanggan Utama' },
  { name: 'nilai_bulanan_pelanggan_2', templates: ['muap'], kind: 'fact-display', source: 'app', description: 'nilai bulanan pelanggan 2', anchor: 'MUAP T34 — Pelanggan Utama' },
  { name: 'metode_pelanggan_2', templates: ['muap'], kind: 'fact-display', source: 'app', description: 'metode pelanggan 2 (free-text: cara checking dilakukan)', anchor: 'MUAP T34 — Pelanggan Utama' },
  { name: 'tanggal_pelanggan_2', templates: ['muap'], kind: 'fact-display', source: 'app', description: 'tanggal pelanggan 2', anchor: 'MUAP T34 — Pelanggan Utama' },
  { name: 'nama_pelanggan_3', templates: ['muap'], kind: 'fact-display', source: 'app', description: 'nama pelanggan 3', anchor: 'MUAP T34 — Pelanggan Utama' },
  { name: 'kota_pelanggan_3', templates: ['muap'], kind: 'fact-display', source: 'app', description: 'kota pelanggan 3', anchor: 'MUAP T34 — Pelanggan Utama' },
  { name: 'lama_relasi_pelanggan_3_tahun', templates: ['muap'], kind: 'fact-display', source: 'app', description: 'lama relasi pelanggan 3 tahun', anchor: 'MUAP T34 — Pelanggan Utama' },
  { name: 'nilai_bulanan_pelanggan_3', templates: ['muap'], kind: 'fact-display', source: 'app', description: 'nilai bulanan pelanggan 3', anchor: 'MUAP T34 — Pelanggan Utama' },
  { name: 'metode_pelanggan_3', templates: ['muap'], kind: 'fact-display', source: 'app', description: 'metode pelanggan 3 (free-text: cara checking dilakukan)', anchor: 'MUAP T34 — Pelanggan Utama' },
  { name: 'tanggal_pelanggan_3', templates: ['muap'], kind: 'fact-display', source: 'app', description: 'tanggal pelanggan 3', anchor: 'MUAP T34 — Pelanggan Utama' },
  // --- MUAP T35 — Pekerjaan Selesai ---
  { name: 'bouwheer_selesai_1', templates: ['muap'], kind: 'fact-display', source: 'app', description: 'bouwheer selesai 1', anchor: 'MUAP T35 — Pekerjaan Selesai' },
  { name: 'nama_pekerjaan_selesai_1', templates: ['muap'], kind: 'fact-display', source: 'app', description: 'nama pekerjaan selesai 1', anchor: 'MUAP T35 — Pekerjaan Selesai' },
  { name: 'nilai_pekerjaan_selesai_1', templates: ['muap'], kind: 'fact-display', source: 'app', description: 'nilai pekerjaan selesai 1', anchor: 'MUAP T35 — Pekerjaan Selesai' },
  { name: 'periode_pekerjaan_selesai_1', templates: ['muap'], kind: 'fact-display', source: 'app', description: 'periode pekerjaan selesai 1', anchor: 'MUAP T35 — Pekerjaan Selesai' },
  { name: 'bouwheer_selesai_2', templates: ['muap'], kind: 'fact-display', source: 'app', description: 'bouwheer selesai 2', anchor: 'MUAP T35 — Pekerjaan Selesai' },
  { name: 'nama_pekerjaan_selesai_2', templates: ['muap'], kind: 'fact-display', source: 'app', description: 'nama pekerjaan selesai 2', anchor: 'MUAP T35 — Pekerjaan Selesai' },
  { name: 'nilai_pekerjaan_selesai_2', templates: ['muap'], kind: 'fact-display', source: 'app', description: 'nilai pekerjaan selesai 2', anchor: 'MUAP T35 — Pekerjaan Selesai' },
  { name: 'periode_pekerjaan_selesai_2', templates: ['muap'], kind: 'fact-display', source: 'app', description: 'periode pekerjaan selesai 2', anchor: 'MUAP T35 — Pekerjaan Selesai' },
  // --- MUAP T36 — Progress Pipeline ---
  { name: 'status_pekerjaan_pipeline_1', templates: ['muap'], kind: 'fact-display', source: 'app', description: 'status pekerjaan pipeline 1', anchor: 'MUAP T36 — Progress Pipeline' },
  { name: 'status_pekerjaan_pipeline_2', templates: ['muap'], kind: 'fact-display', source: 'app', description: 'status pekerjaan pipeline 2', anchor: 'MUAP T36 — Progress Pipeline' },
  { name: 'total_nilai_pekerjaan_on_going', templates: ['muap'], kind: 'fact-calc', source: 'derived', description: 'total nilai pekerjaan on going', anchor: 'MUAP T36 — Progress Pipeline', formula: 'Calculated from related template values at fill time' },
  { name: 'total_nilai_pekerjaan_upcoming', templates: ['muap'], kind: 'fact-calc', source: 'derived', description: 'total nilai pekerjaan upcoming', anchor: 'MUAP T36 — Progress Pipeline', formula: 'Calculated from related template values at fill time' },
  { name: 'ai_status_upcoming_projects', templates: ['muap'], kind: 'narrative-ai', source: 'ai-with-research-context', description: 'ai status upcoming projects', anchor: 'MUAP T36 — Progress Pipeline' },
  // --- MUAP T38 — Supplier ---
  { name: 'nama_supplier_1', templates: ['muap'], kind: 'fact-display', source: 'app', description: 'nama supplier 1', anchor: 'MUAP T38 — Supplier' },
  { name: 'jenis_supplier_1', templates: ['muap'], kind: 'fact-display', source: 'app', description: 'jenis supplier 1', anchor: 'MUAP T38 — Supplier' },
  { name: 'nilai_bulanan_supplier_1', templates: ['muap'], kind: 'fact-display', source: 'app', description: 'nilai bulanan supplier 1', anchor: 'MUAP T38 — Supplier' },
  { name: 'terms_supplier_1', templates: ['muap'], kind: 'fact-display', source: 'app', description: 'terms supplier 1', anchor: 'MUAP T38 — Supplier' },
  { name: 'keterangan_supplier_1', templates: ['muap'], kind: 'fact-display', source: 'app', description: 'keterangan supplier 1', anchor: 'MUAP T38 — Supplier' },
  { name: 'nama_supplier_2', templates: ['muap'], kind: 'fact-display', source: 'app', description: 'nama supplier 2', anchor: 'MUAP T38 — Supplier' },
  { name: 'jenis_supplier_2', templates: ['muap'], kind: 'fact-display', source: 'app', description: 'jenis supplier 2', anchor: 'MUAP T38 — Supplier' },
  { name: 'nilai_bulanan_supplier_2', templates: ['muap'], kind: 'fact-display', source: 'app', description: 'nilai bulanan supplier 2', anchor: 'MUAP T38 — Supplier' },
  { name: 'terms_supplier_2', templates: ['muap'], kind: 'fact-display', source: 'app', description: 'terms supplier 2', anchor: 'MUAP T38 — Supplier' },
  { name: 'keterangan_supplier_2', templates: ['muap'], kind: 'fact-display', source: 'app', description: 'keterangan supplier 2', anchor: 'MUAP T38 — Supplier' },
  // --- MUAP T41 — Laporan Keuangan ---
  { name: 'tahun_laporan_1', templates: ['muap'], kind: 'fact-display', source: 'app', description: 'tahun laporan 1', anchor: 'MUAP T41 — Laporan Keuangan' },
  { name: 'status_audited_or_inhouse_laporan_1', templates: ['muap'], kind: 'categorical', source: 'app', description: 'status audited or inhouse laporan 1', anchor: 'MUAP T41 — Laporan Keuangan', enum: ['Audited', 'Inhouse'] },
  { name: 'periode_laporan_1', templates: ['muap'], kind: 'fact-display', source: 'app', description: 'periode laporan 1', anchor: 'MUAP T41 — Laporan Keuangan' },
  { name: 'kap_or_catatan_laporan_1', templates: ['muap'], kind: 'categorical', source: 'app', description: 'kap or catatan laporan 1', anchor: 'MUAP T41 — Laporan Keuangan', enum: ['Ya', 'Tidak'] },
  { name: 'tahun_laporan_2', templates: ['muap'], kind: 'fact-display', source: 'app', description: 'tahun laporan 2', anchor: 'MUAP T41 — Laporan Keuangan' },
  { name: 'status_audited_or_inhouse_laporan_2', templates: ['muap'], kind: 'categorical', source: 'app', description: 'status audited or inhouse laporan 2', anchor: 'MUAP T41 — Laporan Keuangan', enum: ['Audited', 'Inhouse'] },
  { name: 'periode_laporan_2', templates: ['muap'], kind: 'fact-display', source: 'app', description: 'periode laporan 2', anchor: 'MUAP T41 — Laporan Keuangan' },
  { name: 'kap_or_catatan_laporan_2', templates: ['muap'], kind: 'categorical', source: 'app', description: 'kap or catatan laporan 2', anchor: 'MUAP T41 — Laporan Keuangan', enum: ['Ya', 'Tidak'] },
  { name: 'tahun_laporan_3', templates: ['muap'], kind: 'fact-display', source: 'app', description: 'tahun laporan 3', anchor: 'MUAP T41 — Laporan Keuangan' },
  { name: 'status_audited_or_inhouse_laporan_3', templates: ['muap'], kind: 'categorical', source: 'app', description: 'status audited or inhouse laporan 3', anchor: 'MUAP T41 — Laporan Keuangan', enum: ['Audited', 'Inhouse'] },
  { name: 'periode_laporan_3', templates: ['muap'], kind: 'fact-display', source: 'app', description: 'periode laporan 3', anchor: 'MUAP T41 — Laporan Keuangan' },
  { name: 'kap_or_catatan_laporan_3', templates: ['muap'], kind: 'categorical', source: 'app', description: 'kap or catatan laporan 3', anchor: 'MUAP T41 — Laporan Keuangan', enum: ['Ya', 'Tidak'] },
  // --- MUAP post-T41 ---
  { name: 'ai_audit_kewajiban_catatan', templates: ['muap'], kind: 'narrative-ai', source: 'ai-with-research-context', description: 'ai audit kewajiban catatan', anchor: 'MUAP post-T41' },
  // --- MUAP T43 — Laba Rugi ---
  { name: 'laba_rugi_periode_1', templates: ['muap'], kind: 'fact-display', source: 'app', description: 'laba rugi periode 1', anchor: 'MUAP T43 — Laba Rugi' },
  { name: 'laba_rugi_periode_2', templates: ['muap'], kind: 'fact-display', source: 'app', description: 'laba rugi periode 2', anchor: 'MUAP T43 — Laba Rugi' },
  { name: 'laba_rugi_periode_3', templates: ['muap'], kind: 'fact-display', source: 'app', description: 'laba rugi periode 3', anchor: 'MUAP T43 — Laba Rugi' },
  // --- MUAP post-T43 ---
  { name: 'ai_analisis_tren_keuangan', templates: ['muap'], kind: 'narrative-ai', source: 'ai-with-research-context', description: 'ai analisis tren keuangan', anchor: 'MUAP post-T43' },
  // --- MUAP T45 — Neraca ---
  { name: 'neraca_periode_1', templates: ['muap'], kind: 'fact-display', source: 'app', description: 'neraca periode 1', anchor: 'MUAP T45 — Neraca' },
  { name: 'neraca_kas_setara_p1', templates: ['muap'], kind: 'fact-display', source: 'app', description: 'neraca kas setara p1', anchor: 'MUAP T45 — Neraca' },
  { name: 'neraca_piutang_usaha_p1', templates: ['muap'], kind: 'fact-display', source: 'app', description: 'neraca piutang usaha p1', anchor: 'MUAP T45 — Neraca' },
  { name: 'neraca_persediaan_p1', templates: ['muap'], kind: 'fact-display', source: 'app', description: 'neraca persediaan p1', anchor: 'MUAP T45 — Neraca' },
  { name: 'neraca_aset_lancar_lainnya_p1', templates: ['muap'], kind: 'fact-display', source: 'app', description: 'neraca aset lancar lainnya p1', anchor: 'MUAP T45 — Neraca' },
  { name: 'neraca_aset_tidak_lancar_p1', templates: ['muap'], kind: 'fact-display', source: 'app', description: 'neraca aset tidak lancar p1', anchor: 'MUAP T45 — Neraca' },
  { name: 'neraca_hutang_panjang_p1', templates: ['muap'], kind: 'fact-display', source: 'app', description: 'neraca hutang panjang p1', anchor: 'MUAP T45 — Neraca' },
  { name: 'neraca_modal_disetor_p1', templates: ['muap'], kind: 'fact-display', source: 'app', description: 'neraca modal disetor p1', anchor: 'MUAP T45 — Neraca' },
  { name: 'neraca_laba_ditahan_p1', templates: ['muap'], kind: 'fact-display', source: 'app', description: 'neraca laba ditahan p1', anchor: 'MUAP T45 — Neraca' },
  { name: 'neraca_periode_2', templates: ['muap'], kind: 'fact-display', source: 'app', description: 'neraca periode 2', anchor: 'MUAP T45 — Neraca' },
  { name: 'neraca_kas_setara_p2', templates: ['muap'], kind: 'fact-display', source: 'app', description: 'neraca kas setara p2', anchor: 'MUAP T45 — Neraca' },
  { name: 'neraca_piutang_usaha_p2', templates: ['muap'], kind: 'fact-display', source: 'app', description: 'neraca piutang usaha p2', anchor: 'MUAP T45 — Neraca' },
  { name: 'neraca_persediaan_p2', templates: ['muap'], kind: 'fact-display', source: 'app', description: 'neraca persediaan p2', anchor: 'MUAP T45 — Neraca' },
  { name: 'neraca_aset_lancar_lainnya_p2', templates: ['muap'], kind: 'fact-display', source: 'app', description: 'neraca aset lancar lainnya p2', anchor: 'MUAP T45 — Neraca' },
  { name: 'neraca_aset_tidak_lancar_p2', templates: ['muap'], kind: 'fact-display', source: 'app', description: 'neraca aset tidak lancar p2', anchor: 'MUAP T45 — Neraca' },
  { name: 'neraca_hutang_panjang_p2', templates: ['muap'], kind: 'fact-display', source: 'app', description: 'neraca hutang panjang p2', anchor: 'MUAP T45 — Neraca' },
  { name: 'neraca_modal_disetor_p2', templates: ['muap'], kind: 'fact-display', source: 'app', description: 'neraca modal disetor p2', anchor: 'MUAP T45 — Neraca' },
  { name: 'neraca_laba_ditahan_p2', templates: ['muap'], kind: 'fact-display', source: 'app', description: 'neraca laba ditahan p2', anchor: 'MUAP T45 — Neraca' },
  { name: 'neraca_periode_3', templates: ['muap'], kind: 'fact-display', source: 'app', description: 'neraca periode 3', anchor: 'MUAP T45 — Neraca' },
  { name: 'neraca_kas_setara_p3', templates: ['muap'], kind: 'fact-display', source: 'app', description: 'neraca kas setara p3', anchor: 'MUAP T45 — Neraca' },
  { name: 'neraca_piutang_usaha_p3', templates: ['muap'], kind: 'fact-display', source: 'app', description: 'neraca piutang usaha p3', anchor: 'MUAP T45 — Neraca' },
  { name: 'neraca_persediaan_p3', templates: ['muap'], kind: 'fact-display', source: 'app', description: 'neraca persediaan p3', anchor: 'MUAP T45 — Neraca' },
  { name: 'neraca_aset_lancar_lainnya_p3', templates: ['muap'], kind: 'fact-display', source: 'app', description: 'neraca aset lancar lainnya p3', anchor: 'MUAP T45 — Neraca' },
  { name: 'neraca_aset_tidak_lancar_p3', templates: ['muap'], kind: 'fact-display', source: 'app', description: 'neraca aset tidak lancar p3', anchor: 'MUAP T45 — Neraca' },
  { name: 'neraca_hutang_panjang_p3', templates: ['muap'], kind: 'fact-display', source: 'app', description: 'neraca hutang panjang p3', anchor: 'MUAP T45 — Neraca' },
  { name: 'neraca_modal_disetor_p3', templates: ['muap'], kind: 'fact-display', source: 'app', description: 'neraca modal disetor p3', anchor: 'MUAP T45 — Neraca' },
  { name: 'neraca_laba_ditahan_p3', templates: ['muap'], kind: 'fact-display', source: 'app', description: 'neraca laba ditahan p3', anchor: 'MUAP T45 — Neraca' },
  // --- MUAP post-T45 ---
  { name: 'ai_analisis_neraca_kunci', templates: ['muap'], kind: 'narrative-ai', source: 'ai-with-research-context', description: 'ai analisis neraca kunci', anchor: 'MUAP post-T45' },
  // --- MUAP T47 — Rasio Keuangan ---
  { name: 'rasio_periode_1', templates: ['muap'], kind: 'fact-display', source: 'derived', description: 'rasio periode 1', anchor: 'MUAP T47 — Rasio Keuangan' },
  { name: 'rasio_qr_p1', templates: ['muap'], kind: 'fact-calc', source: 'derived', description: 'rasio qr p1', anchor: 'MUAP T47 — Rasio Keuangan', formula: 'Calculated from related template values at fill time' },
  { name: 'rasio_dar_p1', templates: ['muap'], kind: 'fact-calc', source: 'derived', description: 'rasio dar p1', anchor: 'MUAP T47 — Rasio Keuangan', formula: 'Calculated from related template values at fill time' },
  { name: 'rasio_gpm_p1', templates: ['muap'], kind: 'fact-calc', source: 'derived', description: 'rasio gpm p1', anchor: 'MUAP T47 — Rasio Keuangan', formula: 'Calculated from related template values at fill time' },
  { name: 'rasio_npm_p1', templates: ['muap'], kind: 'fact-calc', source: 'derived', description: 'rasio npm p1', anchor: 'MUAP T47 — Rasio Keuangan', formula: 'Calculated from related template values at fill time' },
  { name: 'rasio_roa_p1', templates: ['muap'], kind: 'fact-calc', source: 'derived', description: 'rasio roa p1', anchor: 'MUAP T47 — Rasio Keuangan', formula: 'Calculated from related template values at fill time' },
  { name: 'rasio_roe_p1', templates: ['muap'], kind: 'fact-calc', source: 'derived', description: 'rasio roe p1', anchor: 'MUAP T47 — Rasio Keuangan', formula: 'Calculated from related template values at fill time' },
  { name: 'rasio_dso_p1', templates: ['muap'], kind: 'fact-calc', source: 'derived', description: 'rasio dso p1', anchor: 'MUAP T47 — Rasio Keuangan', formula: 'Calculated from related template values at fill time' },
  { name: 'rasio_dpo_p1', templates: ['muap'], kind: 'fact-calc', source: 'derived', description: 'rasio dpo p1', anchor: 'MUAP T47 — Rasio Keuangan', formula: 'Calculated from related template values at fill time' },
  { name: 'rasio_dio_p1', templates: ['muap'], kind: 'fact-calc', source: 'derived', description: 'rasio dio p1', anchor: 'MUAP T47 — Rasio Keuangan', formula: 'Calculated from related template values at fill time' },
  { name: 'rasio_ccc_p1', templates: ['muap'], kind: 'fact-calc', source: 'derived', description: 'rasio ccc p1', anchor: 'MUAP T47 — Rasio Keuangan', formula: 'Calculated from related template values at fill time' },
  { name: 'rasio_periode_2', templates: ['muap'], kind: 'fact-display', source: 'derived', description: 'rasio periode 2', anchor: 'MUAP T47 — Rasio Keuangan' },
  { name: 'rasio_qr_p2', templates: ['muap'], kind: 'fact-calc', source: 'derived', description: 'rasio qr p2', anchor: 'MUAP T47 — Rasio Keuangan', formula: 'Calculated from related template values at fill time' },
  { name: 'rasio_dar_p2', templates: ['muap'], kind: 'fact-calc', source: 'derived', description: 'rasio dar p2', anchor: 'MUAP T47 — Rasio Keuangan', formula: 'Calculated from related template values at fill time' },
  { name: 'rasio_gpm_p2', templates: ['muap'], kind: 'fact-calc', source: 'derived', description: 'rasio gpm p2', anchor: 'MUAP T47 — Rasio Keuangan', formula: 'Calculated from related template values at fill time' },
  { name: 'rasio_npm_p2', templates: ['muap'], kind: 'fact-calc', source: 'derived', description: 'rasio npm p2', anchor: 'MUAP T47 — Rasio Keuangan', formula: 'Calculated from related template values at fill time' },
  { name: 'rasio_roa_p2', templates: ['muap'], kind: 'fact-calc', source: 'derived', description: 'rasio roa p2', anchor: 'MUAP T47 — Rasio Keuangan', formula: 'Calculated from related template values at fill time' },
  { name: 'rasio_roe_p2', templates: ['muap'], kind: 'fact-calc', source: 'derived', description: 'rasio roe p2', anchor: 'MUAP T47 — Rasio Keuangan', formula: 'Calculated from related template values at fill time' },
  { name: 'rasio_dso_p2', templates: ['muap'], kind: 'fact-calc', source: 'derived', description: 'rasio dso p2', anchor: 'MUAP T47 — Rasio Keuangan', formula: 'Calculated from related template values at fill time' },
  { name: 'rasio_dpo_p2', templates: ['muap'], kind: 'fact-calc', source: 'derived', description: 'rasio dpo p2', anchor: 'MUAP T47 — Rasio Keuangan', formula: 'Calculated from related template values at fill time' },
  { name: 'rasio_dio_p2', templates: ['muap'], kind: 'fact-calc', source: 'derived', description: 'rasio dio p2', anchor: 'MUAP T47 — Rasio Keuangan', formula: 'Calculated from related template values at fill time' },
  { name: 'rasio_ccc_p2', templates: ['muap'], kind: 'fact-calc', source: 'derived', description: 'rasio ccc p2', anchor: 'MUAP T47 — Rasio Keuangan', formula: 'Calculated from related template values at fill time' },
  { name: 'rasio_periode_3', templates: ['muap'], kind: 'fact-display', source: 'derived', description: 'rasio periode 3', anchor: 'MUAP T47 — Rasio Keuangan' },
  { name: 'rasio_cr_p3', templates: ['muap'], kind: 'fact-calc', source: 'derived', description: 'rasio cr p3', anchor: 'MUAP T47 — Rasio Keuangan', formula: 'Calculated from related template values at fill time' },
  { name: 'rasio_qr_p3', templates: ['muap'], kind: 'fact-calc', source: 'derived', description: 'rasio qr p3', anchor: 'MUAP T47 — Rasio Keuangan', formula: 'Calculated from related template values at fill time' },
  { name: 'rasio_dar_p3', templates: ['muap'], kind: 'fact-calc', source: 'derived', description: 'rasio dar p3', anchor: 'MUAP T47 — Rasio Keuangan', formula: 'Calculated from related template values at fill time' },
  { name: 'rasio_der_p3', templates: ['muap'], kind: 'fact-calc', source: 'derived', description: 'rasio der p3', anchor: 'MUAP T47 — Rasio Keuangan', formula: 'Calculated from related template values at fill time' },
  { name: 'rasio_gpm_p3', templates: ['muap'], kind: 'fact-calc', source: 'derived', description: 'rasio gpm p3', anchor: 'MUAP T47 — Rasio Keuangan', formula: 'Calculated from related template values at fill time' },
  { name: 'rasio_npm_p3', templates: ['muap'], kind: 'fact-calc', source: 'derived', description: 'rasio npm p3', anchor: 'MUAP T47 — Rasio Keuangan', formula: 'Calculated from related template values at fill time' },
  { name: 'rasio_roa_p3', templates: ['muap'], kind: 'fact-calc', source: 'derived', description: 'rasio roa p3', anchor: 'MUAP T47 — Rasio Keuangan', formula: 'Calculated from related template values at fill time' },
  { name: 'rasio_roe_p3', templates: ['muap'], kind: 'fact-calc', source: 'derived', description: 'rasio roe p3', anchor: 'MUAP T47 — Rasio Keuangan', formula: 'Calculated from related template values at fill time' },
  { name: 'rasio_dso_p3', templates: ['muap'], kind: 'fact-calc', source: 'derived', description: 'rasio dso p3', anchor: 'MUAP T47 — Rasio Keuangan', formula: 'Calculated from related template values at fill time' },
  { name: 'rasio_dpo_p3', templates: ['muap'], kind: 'fact-calc', source: 'derived', description: 'rasio dpo p3', anchor: 'MUAP T47 — Rasio Keuangan', formula: 'Calculated from related template values at fill time' },
  { name: 'rasio_dio_p3', templates: ['muap'], kind: 'fact-calc', source: 'derived', description: 'rasio dio p3', anchor: 'MUAP T47 — Rasio Keuangan', formula: 'Calculated from related template values at fill time' },
  { name: 'rasio_ccc_p3', templates: ['muap'], kind: 'fact-calc', source: 'derived', description: 'rasio ccc p3', anchor: 'MUAP T47 — Rasio Keuangan', formula: 'Calculated from related template values at fill time' },
  { name: 'rasio_dscri_p3', templates: ['muap'], kind: 'fact-calc', source: 'derived', description: 'rasio dscri p3', anchor: 'MUAP T47 — Rasio Keuangan', formula: 'Calculated from related template values at fill time' },
  // --- MUAP post-T47 ---
  { name: 'ai_dscri_narasi', templates: ['muap'], kind: 'narrative-ai', source: 'ai-with-research-context', description: 'ai dscri narasi', anchor: 'MUAP post-T47' },
  // --- MUAP T50 — Rekening Koran ---
  { name: 'rekkoran_q1_tahun', templates: ['muap'], kind: 'fact-display', source: 'app', description: 'rekkoran q1 tahun', anchor: 'MUAP T50 — Rekening Koran' },
  { name: 'rekkoran_saldo_q1', templates: ['muap'], kind: 'fact-display', source: 'app', description: 'rekkoran saldo q1', anchor: 'MUAP T50 — Rekening Koran' },
  { name: 'rekkoran_kredit_q1', templates: ['muap'], kind: 'fact-display', source: 'app', description: 'rekkoran kredit q1', anchor: 'MUAP T50 — Rekening Koran' },
  { name: 'rekkoran_debit_q1', templates: ['muap'], kind: 'fact-display', source: 'app', description: 'rekkoran debit q1', anchor: 'MUAP T50 — Rekening Koran' },
  { name: 'rekkoran_pencerminan_q1', templates: ['muap'], kind: 'fact-display', source: 'app', description: 'rekkoran pencerminan q1', anchor: 'MUAP T50 — Rekening Koran' },
  { name: 'rekkoran_q2_tahun', templates: ['muap'], kind: 'fact-display', source: 'app', description: 'rekkoran q2 tahun', anchor: 'MUAP T50 — Rekening Koran' },
  { name: 'rekkoran_saldo_q2', templates: ['muap'], kind: 'fact-display', source: 'app', description: 'rekkoran saldo q2', anchor: 'MUAP T50 — Rekening Koran' },
  { name: 'rekkoran_kredit_q2', templates: ['muap'], kind: 'fact-display', source: 'app', description: 'rekkoran kredit q2', anchor: 'MUAP T50 — Rekening Koran' },
  { name: 'rekkoran_debit_q2', templates: ['muap'], kind: 'fact-display', source: 'app', description: 'rekkoran debit q2', anchor: 'MUAP T50 — Rekening Koran' },
  { name: 'rekkoran_pencerminan_q2', templates: ['muap'], kind: 'fact-display', source: 'app', description: 'rekkoran pencerminan q2', anchor: 'MUAP T50 — Rekening Koran' },
  { name: 'rekkoran_q3_tahun', templates: ['muap'], kind: 'fact-display', source: 'app', description: 'rekkoran q3 tahun', anchor: 'MUAP T50 — Rekening Koran' },
  { name: 'rekkoran_saldo_q3', templates: ['muap'], kind: 'fact-display', source: 'app', description: 'rekkoran saldo q3', anchor: 'MUAP T50 — Rekening Koran' },
  { name: 'rekkoran_kredit_q3', templates: ['muap'], kind: 'fact-display', source: 'app', description: 'rekkoran kredit q3', anchor: 'MUAP T50 — Rekening Koran' },
  { name: 'rekkoran_debit_q3', templates: ['muap'], kind: 'fact-display', source: 'app', description: 'rekkoran debit q3', anchor: 'MUAP T50 — Rekening Koran' },
  { name: 'rekkoran_pencerminan_q3', templates: ['muap'], kind: 'fact-display', source: 'app', description: 'rekkoran pencerminan q3', anchor: 'MUAP T50 — Rekening Koran' },
  { name: 'rekkoran_q4_tahun', templates: ['muap'], kind: 'fact-display', source: 'app', description: 'rekkoran q4 tahun', anchor: 'MUAP T50 — Rekening Koran' },
  { name: 'rekkoran_saldo_q4', templates: ['muap'], kind: 'fact-display', source: 'app', description: 'rekkoran saldo q4', anchor: 'MUAP T50 — Rekening Koran' },
  { name: 'rekkoran_kredit_q4', templates: ['muap'], kind: 'fact-display', source: 'app', description: 'rekkoran kredit q4', anchor: 'MUAP T50 — Rekening Koran' },
  { name: 'rekkoran_debit_q4', templates: ['muap'], kind: 'fact-display', source: 'app', description: 'rekkoran debit q4', anchor: 'MUAP T50 — Rekening Koran' },
  { name: 'rekkoran_pencerminan_q4', templates: ['muap'], kind: 'fact-display', source: 'app', description: 'rekkoran pencerminan q4', anchor: 'MUAP T50 — Rekening Koran' },
  // --- MUAP post-T50/pre-T54 ---
  { name: 'ai_rekening_koran_analisis', templates: ['muap'], kind: 'narrative-ai', source: 'ai-with-research-context', description: 'ai rekening koran analisis', anchor: 'MUAP post-T50/pre-T54' },
  { name: 'ai_kebutuhan_pembiayaan_narratif', templates: ['muap'], kind: 'narrative-ai', source: 'ai-with-research-context', description: 'ai kebutuhan pembiayaan narratif', anchor: 'MUAP post-T50/pre-T54' },
  // --- MUAP T54 — Kebutuhan Modal Kerja ---
  { name: 'basis_pendapatan_or_proyeksi', templates: ['muap'], kind: 'categorical', source: 'app', description: 'basis pendapatan or proyeksi', anchor: 'MUAP T54 — Kebutuhan Modal Kerja', enum: ['Kontrak on-going', 'Proyeksi konservatif'] },
  { name: 'nilai_pendapatan_per_bulan', templates: ['muap'], kind: 'fact-display', source: 'app', description: 'nilai pendapatan per bulan', anchor: 'MUAP T54 — Kebutuhan Modal Kerja' },
  { name: 'persen_pipeline_on_going', templates: ['muap'], kind: 'fact-display', source: 'app', description: 'persen pipeline on going', anchor: 'MUAP T54 — Kebutuhan Modal Kerja' },
  { name: 'persen_dari_kontrak', templates: ['muap'], kind: 'fact-display', source: 'app', description: 'persen dari kontrak', anchor: 'MUAP T54 — Kebutuhan Modal Kerja' },
  { name: 'max_persen_rab', templates: ['muap'], kind: 'fact-display', source: 'app', description: 'max persen rab', anchor: 'MUAP T54 — Kebutuhan Modal Kerja' },
  { name: 'porsi_bank_max_persen', templates: ['muap'], kind: 'fact-display', source: 'app', description: 'porsi bank max persen', anchor: 'MUAP T54 — Kebutuhan Modal Kerja' },
  { name: 'min_self_financing_persen', templates: ['muap'], kind: 'fact-display', source: 'app', description: 'min self financing persen', anchor: 'MUAP T54 — Kebutuhan Modal Kerja' },
  { name: 'nilai_per_siklus', templates: ['muap'], kind: 'fact-display', source: 'app', description: 'nilai per siklus', anchor: 'MUAP T54 — Kebutuhan Modal Kerja' },
  { name: 'nilai_kebutuhan_modal_kerja', templates: ['muap'], kind: 'fact-display', source: 'app', description: 'nilai kebutuhan modal kerja', anchor: 'MUAP T54 — Kebutuhan Modal Kerja' },
  { name: 'ai_validasi_plafond_vs_skala', templates: ['muap'], kind: 'narrative-ai', source: 'ai-with-research-context', description: 'ai validasi plafond vs skala', anchor: 'MUAP T54 — Kebutuhan Modal Kerja' },
  // --- MUAP T56 — Agunan ---
  { name: 'jenis_agunan_utama_1', templates: ['muap'], kind: 'fact-display', source: 'app', description: 'jenis agunan utama 1', anchor: 'MUAP T56 — Agunan' },
  { name: 'jenis_sertifikat_agunan_1', templates: ['muap'], kind: 'fact-display', source: 'app', description: 'jenis sertifikat agunan 1', anchor: 'MUAP T56 — Agunan' },
  { name: 'no_sertifikat_agunan_1', templates: ['muap'], kind: 'fact-display', source: 'app', description: 'no sertifikat agunan 1', anchor: 'MUAP T56 — Agunan' },
  { name: 'atas_nama_utama_1', templates: ['muap'], kind: 'fact-display', source: 'app', description: 'atas nama utama 1', anchor: 'MUAP T56 — Agunan' },
  { name: 'lokasi_utama_1', templates: ['muap'], kind: 'fact-display', source: 'app', description: 'lokasi utama 1', anchor: 'MUAP T56 — Agunan' },
  { name: 'luas_tanah_utama_1_m2', templates: ['muap'], kind: 'fact-display', source: 'app', description: 'luas tanah utama 1 m2', anchor: 'MUAP T56 — Agunan' },
  { name: 'luas_bangunan_utama_1_m2', templates: ['muap'], kind: 'fact-display', source: 'app', description: 'luas bangunan utama 1 m2', anchor: 'MUAP T56 — Agunan' },
  { name: 'nilai_pasar_tanah_utama_1', templates: ['muap'], kind: 'fact-display', source: 'app', description: 'nilai pasar tanah utama 1', anchor: 'MUAP T56 — Agunan' },
  { name: 'nilai_pasar_bangunan_utama_1', templates: ['muap'], kind: 'fact-display', source: 'app', description: 'nilai pasar bangunan utama 1', anchor: 'MUAP T56 — Agunan' },
  { name: 'nilai_cev_tanah_utama_1', templates: ['muap'], kind: 'fact-display', source: 'app', description: 'nilai cev tanah utama 1', anchor: 'MUAP T56 — Agunan' },
  { name: 'nilai_cev_bangunan_utama_1', templates: ['muap'], kind: 'fact-display', source: 'app', description: 'nilai cev bangunan utama 1', anchor: 'MUAP T56 — Agunan' },
  { name: 'jenis_agunan_utama_2', templates: ['muap'], kind: 'fact-display', source: 'app', description: 'jenis agunan utama 2', anchor: 'MUAP T56 — Agunan' },
  { name: 'jenis_sertifikat_agunan_2', templates: ['muap'], kind: 'fact-display', source: 'app', description: 'jenis sertifikat agunan 2', anchor: 'MUAP T56 — Agunan' },
  { name: 'no_sertifikat_agunan_2', templates: ['muap'], kind: 'fact-display', source: 'app', description: 'no sertifikat agunan 2', anchor: 'MUAP T56 — Agunan' },
  { name: 'atas_nama_utama_2', templates: ['muap'], kind: 'fact-display', source: 'app', description: 'atas nama utama 2', anchor: 'MUAP T56 — Agunan' },
  { name: 'lokasi_utama_2', templates: ['muap'], kind: 'fact-display', source: 'app', description: 'lokasi utama 2', anchor: 'MUAP T56 — Agunan' },
  { name: 'luas_tanah_utama_2_m2', templates: ['muap'], kind: 'fact-display', source: 'app', description: 'luas tanah utama 2 m2', anchor: 'MUAP T56 — Agunan' },
  { name: 'luas_bangunan_utama_2_m2', templates: ['muap'], kind: 'fact-display', source: 'app', description: 'luas bangunan utama 2 m2', anchor: 'MUAP T56 — Agunan' },
  { name: 'nilai_pasar_tanah_utama_2', templates: ['muap'], kind: 'fact-display', source: 'app', description: 'nilai pasar tanah utama 2', anchor: 'MUAP T56 — Agunan' },
  { name: 'nilai_pasar_bangunan_utama_2', templates: ['muap'], kind: 'fact-display', source: 'app', description: 'nilai pasar bangunan utama 2', anchor: 'MUAP T56 — Agunan' },
  { name: 'nilai_cev_tanah_utama_2', templates: ['muap'], kind: 'fact-display', source: 'app', description: 'nilai cev tanah utama 2', anchor: 'MUAP T56 — Agunan' },
  { name: 'nilai_cev_bangunan_utama_2', templates: ['muap'], kind: 'fact-display', source: 'app', description: 'nilai cev bangunan utama 2', anchor: 'MUAP T56 — Agunan' },
  { name: 'cash_collateral_persen_plafond', templates: ['muap'], kind: 'fact-display', source: 'app', description: 'cash collateral persen plafond', anchor: 'MUAP T56 — Agunan' },
  { name: 'cash_collateral_nilai_pasar', templates: ['muap'], kind: 'fact-display', source: 'app', description: 'cash collateral nilai pasar', anchor: 'MUAP T56 — Agunan' },
  { name: 'cash_collateral_nilai_cev', templates: ['muap'], kind: 'fact-display', source: 'app', description: 'cash collateral nilai cev', anchor: 'MUAP T56 — Agunan' },
  { name: 'piutang_proyek_nilai_pasar', templates: ['muap'], kind: 'fact-display', source: 'app', description: 'piutang proyek nilai pasar', anchor: 'MUAP T56 — Agunan' },
  { name: 'piutang_proyek_nilai_cev', templates: ['muap'], kind: 'fact-display', source: 'app', description: 'piutang proyek nilai cev', anchor: 'MUAP T56 — Agunan' },
  { name: 'nama_personal_guarantor', templates: ['muap'], kind: 'fact-display', source: 'app', description: 'nama personal guarantor', anchor: 'MUAP T56 — Agunan' },
  { name: 'jabatan_personal_guarantor', templates: ['muap'], kind: 'fact-display', source: 'app', description: 'jabatan personal guarantor', anchor: 'MUAP T56 — Agunan' },
  { name: 'total_nilai_pasar_agunan', templates: ['muap'], kind: 'fact-calc', source: 'derived', description: 'total nilai pasar agunan', anchor: 'MUAP T56 — Agunan', formula: 'Calculated from related template values at fill time' },
  { name: 'total_nilai_cev_agunan', templates: ['muap', 'rsk'], kind: 'fact-calc', source: 'derived', description: 'total nilai cev agunan', anchor: 'MUAP T56 — Agunan', formula: 'Calculated from related template values at fill time' },
  { name: 'total_nilai_pasar_agunan_utama_saja', templates: ['muap'], kind: 'fact-calc', source: 'derived', description: 'total nilai pasar agunan utama saja', anchor: 'MUAP T56 — Agunan', formula: 'Calculated from related template values at fill time' },
  { name: 'coverage_persen_agunan', templates: ['muap'], kind: 'fact-calc', source: 'derived', description: 'coverage persen agunan', anchor: 'MUAP T56 — Agunan', formula: 'Calculated from related template values at fill time' },
  { name: 'sccr_persen', templates: ['muap'], kind: 'fact-calc', source: 'derived', description: 'sccr persen', anchor: 'MUAP T56 — Agunan', formula: 'Calculated from related template values at fill time' },
  { name: 'ai_collateral_status_narratif', templates: ['muap'], kind: 'narrative-ai', source: 'ai-with-research-context', description: 'ai collateral status narratif', anchor: 'MUAP T56 — Agunan' },
  // --- MUAP T61 — Akad & Fatwa ---
  { name: 'akad_yang_digunakan', templates: ['muap', 'rsk'], kind: 'categorical', source: 'app', description: 'akad yang digunakan', anchor: 'MUAP T61 — Akad & Fatwa', enum: ['Murabahah', 'Musyarakah', 'Ijarah', 'IMBT', 'Istishna', 'Salam'] },
  { name: 'no_fatwa_dsn_mui', templates: ['muap'], kind: 'fact-display', source: 'app', description: 'no fatwa dsn mui', anchor: 'MUAP T61 — Akad & Fatwa' },
  { name: 'nama_fatwa_dsn_mui', templates: ['muap'], kind: 'fact-display', source: 'app', description: 'nama fatwa dsn mui', anchor: 'MUAP T61 — Akad & Fatwa' },
  { name: 'kesesuaian_fatwa_or_tidak', templates: ['muap'], kind: 'categorical', source: 'app', description: 'kesesuaian fatwa or tidak', anchor: 'MUAP T61 — Akad & Fatwa', enum: ['Sesuai', 'Tidak Sesuai'] },
  { name: 'ai_kesesuaian_fatwa_penjelasan', templates: ['muap'], kind: 'narrative-ai', source: 'ai-with-research-context', description: 'ai kesesuaian fatwa penjelasan', anchor: 'MUAP T61 — Akad & Fatwa' },
  { name: 'ai_substansi_ekonomi_akad', templates: ['muap', 'rsk'], kind: 'narrative-ai', source: 'ai-with-research-context', description: 'ai substansi ekonomi akad', anchor: 'MUAP T61 — Akad & Fatwa' },
  { name: 'gharar_riba_maysir_or_tidak_ada', templates: ['muap', 'rsk'], kind: 'categorical', source: 'app', description: 'gharar riba maysir or tidak ada', anchor: 'MUAP T61 — Akad & Fatwa', enum: ['Ada', 'Tidak Ada'] },
  { name: 'ai_gharar_riba_maysir_penjelasan', templates: ['muap', 'rsk'], kind: 'narrative-ai', source: 'ai-with-research-context', description: 'ai gharar riba maysir penjelasan', anchor: 'MUAP T61 — Akad & Fatwa' },
  { name: 'kesesuaian_akad_or', templates: ['muap', 'rsk'], kind: 'categorical', source: 'app', description: 'kesesuaian akad or', anchor: 'MUAP T61 — Akad & Fatwa', enum: ['Sesuai', 'Tidak Sesuai'] },
  // --- MUAP T63 — Syariah ---
  { name: 'kehalalan_usaha', templates: ['muap'], kind: 'categorical', source: 'app', description: 'kehalalan usaha', anchor: 'MUAP T63 — Syariah', enum: ['Halal', 'Halal Bersyarat', 'Perlu Klarifikasi'] },
  { name: 'persen_halal_income', templates: ['muap', 'rsk'], kind: 'fact-display', source: 'app', description: 'persen halal income', anchor: 'MUAP T63 — Syariah' },
  { name: 'ai_halal_income_sumber', templates: ['muap', 'rsk'], kind: 'narrative-ai', source: 'ai-with-research-context', description: 'ai halal income sumber', anchor: 'MUAP T63 — Syariah' },
  { name: 'sertifikat_halal_status', templates: ['muap'], kind: 'categorical', source: 'app', description: 'sertifikat halal status', anchor: 'MUAP T63 — Syariah', enum: ['Ada', 'Tidak Ada', 'Dalam Proses'] },
  { name: 'no_sertifikat_halal', templates: ['muap'], kind: 'fact-display', source: 'app', description: 'no sertifikat halal', anchor: 'MUAP T63 — Syariah' },
  { name: 'pelanggaran_syariah_or_tidak_ada', templates: ['muap'], kind: 'categorical', source: 'app', description: 'pelanggaran syariah or tidak ada', anchor: 'MUAP T63 — Syariah', enum: ['Ada', 'Tidak Ada'] },
  { name: 'ai_pelanggaran_syariah_deskripsi', templates: ['muap'], kind: 'narrative-ai', source: 'ai-with-research-context', description: 'ai pelanggaran syariah deskripsi', anchor: 'MUAP T63 — Syariah' },
  { name: 'rekomendasi_dps_or_tidak', templates: ['muap', 'rsk'], kind: 'categorical', source: 'app', description: 'rekomendasi dps or tidak', anchor: 'MUAP T63 — Syariah', enum: ['Diperlukan', 'Tidak Diperlukan'] },
  { name: 'ai_rekomendasi_dps_alasan', templates: ['muap', 'rsk'], kind: 'narrative-ai', source: 'ai-with-research-context', description: 'ai rekomendasi dps alasan', anchor: 'MUAP T63 — Syariah' },
  { name: 'ai_syariah_opini_narratif', templates: ['muap'], kind: 'narrative-ai', source: 'ai-with-research-context', description: 'ai syariah opini narratif', anchor: 'MUAP T63 — Syariah' },
  { name: 'ai_kehalalan_pendapatan_pastikan', templates: ['muap'], kind: 'narrative-ai', source: 'ai-with-research-context', description: 'ai kehalalan pendapatan pastikan', anchor: 'MUAP T63 — Syariah' },
  // --- MUAP T66 — Line Facility ---
  { name: 'plafond_line_facility', templates: ['muap'], kind: 'fact-display', source: 'app', description: 'plafond line facility', anchor: 'MUAP T66 — Line Facility' },
  { name: 'plafond_line_facility_terbilang', templates: ['muap'], kind: 'fact-display', source: 'app', description: 'plafond line facility terbilang', anchor: 'MUAP T66 — Line Facility' },
  { name: 'tenor_line_facility_bulan', templates: ['muap'], kind: 'fact-display', source: 'app', description: 'tenor line facility bulan', anchor: 'MUAP T66 — Line Facility' },
  { name: 'tenor_line_facility_terbilang', templates: ['muap'], kind: 'fact-display', source: 'app', description: 'tenor line facility terbilang', anchor: 'MUAP T66 — Line Facility' },
  { name: 'tujuan_line_facility_kerja_or_investasi', templates: ['muap'], kind: 'categorical', source: 'app', description: 'tujuan line facility kerja or investasi', anchor: 'MUAP T66 — Line Facility', enum: ['Modal Kerja', 'Investasi'] },
  { name: 'ai_line_facility_deskripsi_penggunaan', templates: ['muap'], kind: 'narrative-ai', source: 'ai-with-research-context', description: 'ai line facility deskripsi penggunaan', anchor: 'MUAP T66 — Line Facility' },
  { name: 'dasar_penarikan_line_facility', templates: ['muap'], kind: 'fact-display', source: 'app', description: 'dasar penarikan line facility', anchor: 'MUAP T66 — Line Facility' },
  { name: 'equivalent_pa_line_facility', templates: ['muap'], kind: 'fact-display', source: 'app', description: 'equivalent pa line facility', anchor: 'MUAP T66 — Line Facility' },
  { name: 'bentuk_line_facility_revolving_or_non_revolving', templates: ['muap', 'rsk'], kind: 'categorical', source: 'app', description: 'bentuk line facility revolving or non revolving', anchor: 'MUAP T66 — Line Facility', enum: ['Revolving', 'Non-Revolving'] },
  { name: 'pengikatan_line_facility_notariil_or_un_notariil', templates: ['muap'], kind: 'categorical', source: 'app', description: 'pengikatan line facility notariil or un notariil', anchor: 'MUAP T66 — Line Facility', enum: ['Notariil', 'Un-Notariil'] },
  // --- MUAP T68 — Realisasi ---
  { name: 'akad_realisasi', templates: ['muap'], kind: 'categorical', source: 'app', description: 'akad realisasi', anchor: 'MUAP T68 — Realisasi', enum: ['Murabahah', 'Musyarakah', 'Ijarah', 'IMBT', 'Istishna', 'Salam'] },
  { name: 'plafond_realisasi', templates: ['muap'], kind: 'fact-display', source: 'app', description: 'plafond realisasi', anchor: 'MUAP T68 — Realisasi' },
  { name: 'plafond_realisasi_terbilang', templates: ['muap'], kind: 'fact-display', source: 'app', description: 'plafond realisasi terbilang', anchor: 'MUAP T68 — Realisasi' },
  { name: 'ai_realisasi_deskripsi_penggunaan', templates: ['muap'], kind: 'narrative-ai', source: 'ai-with-research-context', description: 'ai realisasi deskripsi penggunaan', anchor: 'MUAP T68 — Realisasi' },
  { name: 'tenor_realisasi_bulan', templates: ['muap'], kind: 'fact-display', source: 'app', description: 'tenor realisasi bulan', anchor: 'MUAP T68 — Realisasi' },
  { name: 'tenor_realisasi_terbilang', templates: ['muap'], kind: 'fact-display', source: 'app', description: 'tenor realisasi terbilang', anchor: 'MUAP T68 — Realisasi' },
  { name: 'max_persen_rab_realisasi', templates: ['muap'], kind: 'fact-display', source: 'app', description: 'max persen rab realisasi', anchor: 'MUAP T68 — Realisasi' },
  { name: 'equivalent_pa_realisasi', templates: ['muap', 'rsk'], kind: 'fact-display', source: 'app', description: 'equivalent pa realisasi', anchor: 'MUAP T68 — Realisasi' },
  { name: 'jadwal_angsuran_bulanan_or_sekaligus', templates: ['muap'], kind: 'categorical', source: 'app', description: 'jadwal angsuran bulanan or sekaligus', anchor: 'MUAP T68 — Realisasi', enum: ['Bulanan', 'Sekaligus di akhir'] },
  { name: 'pengikatan_realisasi_notariil_or_un_notariil', templates: ['muap'], kind: 'categorical', source: 'app', description: 'pengikatan realisasi notariil or un notariil', anchor: 'MUAP T68 — Realisasi', enum: ['Notariil', 'Un-Notariil'] },
  // --- MUAP T70/post-T70 ---
  { name: 'biaya_administrasi_pembiayaan_flat', templates: ['muap'], kind: 'fact-display', source: 'app', description: 'biaya administrasi pembiayaan flat', anchor: 'MUAP T70/post-T70' },
  { name: 'ai_uraian_agunan_lengkap', templates: ['muap'], kind: 'narrative-ai', source: 'ai-with-research-context', description: 'ai uraian agunan lengkap', anchor: 'MUAP T70/post-T70' },
  { name: 'ai_uraian_collateral_lainnya', templates: ['muap'], kind: 'narrative-ai', source: 'ai-with-research-context', description: 'ai uraian collateral lainnya', anchor: 'MUAP T70/post-T70' },
  { name: 'max_persen_rab_bank', templates: ['muap'], kind: 'fact-display', source: 'app', description: 'max persen rab bank', anchor: 'MUAP T70/post-T70' },
  { name: 'min_persen_self_financing', templates: ['muap'], kind: 'fact-display', source: 'app', description: 'min persen self financing', anchor: 'MUAP T70/post-T70' },
  { name: 'max_persen_reimbursement', templates: ['muap'], kind: 'fact-display', source: 'app', description: 'max persen reimbursement', anchor: 'MUAP T70/post-T70' },
  { name: 'mekanisme_reimbursement_or_non_reimbursement', templates: ['muap'], kind: 'categorical', source: 'app', description: 'mekanisme reimbursement or non reimbursement', anchor: 'MUAP T70/post-T70', enum: ['Reimbursement', 'Non-Reimbursement'] },
  // --- MUAP post-T70 — Pengikatan ---
  { name: 'pengikatan_tanah_notariil_or_un_notariil', templates: ['muap'], kind: 'categorical', source: 'app', description: 'pengikatan tanah notariil or un notariil', anchor: 'MUAP post-T70 — Pengikatan', enum: ['Notariil', 'Un-Notariil'] },
  { name: 'pengikatan_bangunan_notariil_or_un_notariil', templates: ['muap'], kind: 'categorical', source: 'app', description: 'pengikatan bangunan notariil or un notariil', anchor: 'MUAP post-T70 — Pengikatan', enum: ['Notariil', 'Un-Notariil'] },
  { name: 'pengikatan_mesin_notariil_or_un_notariil', templates: ['muap'], kind: 'categorical', source: 'app', description: 'pengikatan mesin notariil or un notariil', anchor: 'MUAP post-T70 — Pengikatan', enum: ['Notariil', 'Un-Notariil'] },
  { name: 'pengikatan_kendaraan_notariil_or_un_notariil', templates: ['muap'], kind: 'categorical', source: 'app', description: 'pengikatan kendaraan notariil or un notariil', anchor: 'MUAP post-T70 — Pengikatan', enum: ['Notariil', 'Un-Notariil'] },
  { name: 'pengikatan_piutang_notariil_or_un_notariil', templates: ['muap'], kind: 'categorical', source: 'app', description: 'pengikatan piutang notariil or un notariil', anchor: 'MUAP post-T70 — Pengikatan', enum: ['Notariil', 'Un-Notariil'] },
  { name: 'pengikatan_cash_collateral_notariil_or_un_notariil', templates: ['muap'], kind: 'categorical', source: 'app', description: 'pengikatan cash collateral notariil or un notariil', anchor: 'MUAP post-T70 — Pengikatan', enum: ['Notariil', 'Un-Notariil'] },
  // --- MUAP T82-T83 ---
  { name: 'rekomendasi_analis', templates: ['muap'], kind: 'categorical', source: 'app', description: 'rekomendasi analis', anchor: 'MUAP T82-T83', enum: ['SETUJU', 'SETUJU BERSYARAT', 'TIDAK SETUJU'] },
  { name: 'ai_rekomendasi_analis_alasan', templates: ['muap'], kind: 'narrative-ai', source: 'ai-with-research-context', description: 'ai rekomendasi analis alasan', anchor: 'MUAP T82-T83' },
  { name: 'jenis_fasilitas_kesimpulan', templates: ['muap'], kind: 'fact-display', source: 'app', description: 'jenis fasilitas kesimpulan', anchor: 'MUAP T82-T83' },
  { name: 'risk_rating_kesimpulan', templates: ['muap'], kind: 'categorical', source: 'app', description: 'risk rating kesimpulan', anchor: 'MUAP T82-T83', enum: ['Low', 'Moderate', 'Moderate to High', 'High'] },
  { name: 'jenis_agunan_kesimpulan', templates: ['muap'], kind: 'fact-display', source: 'app', description: 'jenis agunan kesimpulan', anchor: 'MUAP T82-T83' },
  // --- MUAP T86 — Deviasi RAC ---
  { name: 'deviasi_rac_1_jenis', templates: ['muap'], kind: 'fact-display', source: 'app', description: 'deviasi rac 1 jenis', anchor: 'MUAP T86 — Deviasi RAC' },
  { name: 'deviasi_rac_1_ketentuan', templates: ['muap'], kind: 'fact-display', source: 'app', description: 'deviasi rac 1 ketentuan', anchor: 'MUAP T86 — Deviasi RAC' },
  { name: 'ai_deviasi_rac_1_kondisi_mitigant', templates: ['muap'], kind: 'narrative-ai', source: 'ai-with-research-context', description: 'ai deviasi rac 1 kondisi mitigant', anchor: 'MUAP T86 — Deviasi RAC' },
  { name: 'deviasi_rac_2_jenis', templates: ['muap'], kind: 'fact-display', source: 'app', description: 'deviasi rac 2 jenis', anchor: 'MUAP T86 — Deviasi RAC' },
  { name: 'deviasi_rac_2_ketentuan', templates: ['muap'], kind: 'fact-display', source: 'app', description: 'deviasi rac 2 ketentuan', anchor: 'MUAP T86 — Deviasi RAC' },
  { name: 'ai_deviasi_rac_2_kondisi_mitigant', templates: ['muap'], kind: 'narrative-ai', source: 'ai-with-research-context', description: 'ai deviasi rac 2 kondisi mitigant', anchor: 'MUAP T86 — Deviasi RAC' },
  { name: 'deviasi_rac_3_jenis', templates: ['muap'], kind: 'fact-display', source: 'app', description: 'deviasi rac 3 jenis', anchor: 'MUAP T86 — Deviasi RAC' },
  { name: 'deviasi_rac_3_ketentuan', templates: ['muap'], kind: 'fact-display', source: 'app', description: 'deviasi rac 3 ketentuan', anchor: 'MUAP T86 — Deviasi RAC' },
  { name: 'ai_deviasi_rac_3_kondisi_mitigant', templates: ['muap'], kind: 'narrative-ai', source: 'ai-with-research-context', description: 'ai deviasi rac 3 kondisi mitigant', anchor: 'MUAP T86 — Deviasi RAC' },
  // --- MUAP T87/Footer ---
  { name: 'kategori_fasilitas', templates: ['muap'], kind: 'categorical', source: 'app', description: 'kategori fasilitas', anchor: 'MUAP T87/Footer', enum: ['Baru', 'Perpanjangan', 'Tambahan'] },
  { name: 'tujuan_jenis_akad_form', templates: ['muap'], kind: 'fact-display', source: 'app', description: 'tujuan jenis akad form', anchor: 'MUAP T87/Footer' },
  { name: 'tanggal_ttd_rm', templates: ['muap'], kind: 'fact-display', source: 'app', description: 'tanggal ttd rm', anchor: 'MUAP T87/Footer' },
  { name: 'nama_rm', templates: ['muap'], kind: 'fact-display', source: 'app', description: 'nama rm', anchor: 'MUAP T87/Footer' },
  { name: 'tanggal_ttd_tl_spv', templates: ['muap'], kind: 'fact-display', source: 'app', description: 'tanggal ttd tl spv', anchor: 'MUAP T87/Footer' },
  { name: 'nama_tl_spv', templates: ['muap'], kind: 'fact-display', source: 'app', description: 'nama tl spv', anchor: 'MUAP T87/Footer' },
  { name: 'tanggal_ttd_bm_ku', templates: ['muap'], kind: 'fact-display', source: 'app', description: 'tanggal ttd bm ku', anchor: 'MUAP T87/Footer' },
  { name: 'nama_bm_ku', templates: ['muap'], kind: 'fact-display', source: 'app', description: 'nama bm ku', anchor: 'MUAP T87/Footer' },
  { name: 'footer_bulan_tahun', templates: ['muap'], kind: 'fact-display', source: 'app', description: 'footer bulan tahun', anchor: 'MUAP T87/Footer' },
  // --- Master reconciliation (2026.06.04): {{token}} literals present in the live MUAP master that
  // the registry lacked. Per AGENTS.md the Hijra template is the LITERAL source of truth, so the
  // registry adopts them (unblocks setup-v2-named-ranges --apply). Fact-display, app-sourced.
  { name: 'no_muap_seq', templates: ['muap'], kind: 'fact-display', source: 'app', description: 'no muap — nomor urut', anchor: 'MUAP T2-T6 (master)' },
  { name: 'no_muap_cabang', templates: ['muap'], kind: 'fact-display', source: 'app', description: 'no muap — kode cabang', anchor: 'MUAP T2-T6 (master)' },
  { name: 'inisial_perusahaan', templates: ['muap'], kind: 'fact-display', source: 'app', description: 'inisial perusahaan', anchor: 'MUAP T2-T6 (master)' },
  { name: 'tanggal_menjadi_nasabah', templates: ['muap'], kind: 'fact-display', source: 'app', description: 'tanggal menjadi nasabah', anchor: 'MUAP T2-T6 (master)' },
  { name: 'key_person_1_nama', templates: ['muap'], kind: 'fact-display', source: 'app', description: 'key person 1 nama', anchor: 'MUAP identitas (master)' },
  { name: 'key_person_1_jabatan', templates: ['muap'], kind: 'fact-display', source: 'app', description: 'key person 1 jabatan', anchor: 'MUAP identitas (master)' },
  { name: 'key_person_2_nama', templates: ['muap'], kind: 'fact-display', source: 'app', description: 'key person 2 nama', anchor: 'MUAP identitas (master)' },
  { name: 'key_person_2_jabatan', templates: ['muap'], kind: 'fact-display', source: 'app', description: 'key person 2 jabatan', anchor: 'MUAP identitas (master)' },
  { name: 'keterangan_pelanggan_2', templates: ['muap'], kind: 'fact-display', source: 'app', description: 'keterangan pelanggan 2', anchor: 'MUAP pelanggan (master)' },
  { name: 'keterangan_pelanggan_3', templates: ['muap'], kind: 'fact-display', source: 'app', description: 'keterangan pelanggan 3', anchor: 'MUAP pelanggan (master)' },
]
