/**
 * RSK-only tokens — transcribed from docs/designs/rsk-v2-tokenization.md rev 2.1.
 * Every entry is rsk_* or ai_rsk_* by registry invariant.
 */
import type { TemplateToken } from './types'

export const RSK_ONLY_TOKENS: ReadonlyArray<TemplateToken> = [
  // --- RSK Header/Identity ---
  { name: 'rsk_no', templates: ['rsk'], kind: 'fact-display', source: 'analyst', description: 'rsk no', anchor: 'RSK Header/Identity' },
  { name: 'rsk_divisi', templates: ['rsk'], kind: 'fact-display', source: 'analyst', description: 'rsk divisi', anchor: 'RSK Header/Identity' },
  { name: 'rsk_bulan_terbit', templates: ['rsk'], kind: 'fact-display', source: 'analyst', description: 'rsk bulan terbit', anchor: 'RSK Header/Identity' },
  { name: 'rsk_tahun_terbit', templates: ['rsk'], kind: 'fact-display', source: 'analyst', description: 'rsk tahun terbit', anchor: 'RSK Header/Identity' },
  { name: 'rsk_tanggal_terbit', templates: ['rsk'], kind: 'fact-display', source: 'analyst', description: 'rsk tanggal terbit', anchor: 'RSK Header/Identity' },
  { name: 'rsk_reviewer_nama', templates: ['rsk'], kind: 'fact-display', source: 'analyst', description: 'rsk reviewer nama', anchor: 'RSK Header/Identity' },
  { name: 'rsk_pengusul_nama', templates: ['rsk'], kind: 'fact-display', source: 'analyst', description: 'rsk pengusul nama', anchor: 'RSK Header/Identity' },
  { name: 'rsk_badan_hukum_or', templates: ['rsk'], kind: 'categorical', source: 'analyst', description: 'rsk badan hukum or', anchor: 'RSK Header/Identity', enum: ['PT', 'CV', 'Firma', 'Perorangan'] },
  { name: 'rsk_status_pajak_or', templates: ['rsk'], kind: 'categorical', source: 'analyst', description: 'Wajib Pajak Badan status (RSK §II.1 T6 r8) — Aktif/Suspended/PKP', anchor: 'RSK §II.1 T6 r8', enum: ['Aktif', 'Suspended', 'PKP'] },
  { name: 'rsk_kategori_halal_usaha_or', templates: ['rsk'], kind: 'categorical', source: 'analyst', description: 'rsk kategori halal usaha or', anchor: 'RSK Header/Identity', enum: ['Halal', 'Haram', 'Borderline'] },
  { name: 'ai_rsk_izin_sektoral_keterangan', templates: ['rsk'], kind: 'narrative-ai', source: 'ai-narrative', description: 'ai rsk izin sektoral keterangan', anchor: 'RSK Header/Identity' },
  // --- RSK T2 — Recommendation badge ---
  { name: 'rsk_keputusan', templates: ['rsk'], kind: 'categorical', source: 'analyst', description: 'rsk keputusan', anchor: 'RSK T2 — Recommendation badge', enum: ['DISETUJUI', 'DISETUJUI DENGAN SYARAT', 'DITOLAK'] },
  // --- RSK §I.2 — Facility table ---
  { name: 'rsk_fac_1_jenis', templates: ['rsk'], kind: 'fact-display', source: 'analyst', description: 'rsk fac 1 jenis', anchor: 'RSK §I.2 — Facility table' },
  { name: 'rsk_fac_1_limit', templates: ['rsk'], kind: 'fact-display', source: 'analyst', description: 'rsk fac 1 limit', anchor: 'RSK §I.2 — Facility table' },
  { name: 'rsk_fac_1_akad', templates: ['rsk'], kind: 'fact-display', source: 'analyst', description: 'rsk fac 1 akad', anchor: 'RSK §I.2 — Facility table' },
  { name: 'rsk_fac_1_tarif', templates: ['rsk'], kind: 'fact-display', source: 'analyst', description: 'rsk fac 1 tarif', anchor: 'RSK §I.2 — Facility table' },
  { name: 'rsk_fac_1_tujuan', templates: ['rsk'], kind: 'fact-display', source: 'analyst', description: 'rsk fac 1 tujuan', anchor: 'RSK §I.2 — Facility table' },
  { name: 'rsk_fac_2_jenis', templates: ['rsk'], kind: 'fact-display', source: 'analyst', description: 'rsk fac 2 jenis', anchor: 'RSK §I.2 — Facility table' },
  { name: 'rsk_fac_2_limit', templates: ['rsk'], kind: 'fact-display', source: 'analyst', description: 'rsk fac 2 limit', anchor: 'RSK §I.2 — Facility table' },
  { name: 'rsk_fac_2_akad', templates: ['rsk'], kind: 'fact-display', source: 'analyst', description: 'rsk fac 2 akad', anchor: 'RSK §I.2 — Facility table' },
  { name: 'rsk_fac_2_tarif', templates: ['rsk'], kind: 'fact-display', source: 'analyst', description: 'rsk fac 2 tarif', anchor: 'RSK §I.2 — Facility table' },
  { name: 'rsk_fac_2_tujuan', templates: ['rsk'], kind: 'fact-display', source: 'analyst', description: 'rsk fac 2 tujuan', anchor: 'RSK §I.2 — Facility table' },
  // --- RSK §I.3 — Deviasi RAC ---
  { name: 'rsk_deviasi_1_isu', templates: ['rsk'], kind: 'fact-display', source: 'analyst', description: 'rsk deviasi 1 isu', anchor: 'RSK §I.3 — Deviasi RAC' },
  { name: 'rsk_deviasi_1_kategori_or', templates: ['rsk'], kind: 'categorical', source: 'analyst', description: 'rsk deviasi 1 kategori or', anchor: 'RSK §I.3 — Deviasi RAC', enum: ['RED FLAG KEUANGAN', 'RED FLAG AGUNAN', 'RED FLAG BISNIS', 'RED FLAG SYARIAH', 'RED FLAG MANAJEMEN', 'RED FLAG LEGAL'] },
  { name: 'ai_rsk_deviasi_1_mitigasi', templates: ['rsk'], kind: 'narrative-ai', source: 'ai-narrative', description: 'ai rsk deviasi 1 mitigasi', anchor: 'RSK §I.3 — Deviasi RAC' },
  { name: 'rsk_deviasi_2_isu', templates: ['rsk'], kind: 'fact-display', source: 'analyst', description: 'rsk deviasi 2 isu', anchor: 'RSK §I.3 — Deviasi RAC' },
  { name: 'rsk_deviasi_2_kategori_or', templates: ['rsk'], kind: 'categorical', source: 'analyst', description: 'rsk deviasi 2 kategori or', anchor: 'RSK §I.3 — Deviasi RAC', enum: ['RED FLAG KEUANGAN', 'RED FLAG AGUNAN', 'RED FLAG BISNIS', 'RED FLAG SYARIAH', 'RED FLAG MANAJEMEN', 'RED FLAG LEGAL'] },
  { name: 'ai_rsk_deviasi_2_mitigasi', templates: ['rsk'], kind: 'narrative-ai', source: 'ai-narrative', description: 'ai rsk deviasi 2 mitigasi', anchor: 'RSK §I.3 — Deviasi RAC' },
  { name: 'ai_rsk_deviasi_3_mitigasi', templates: ['rsk'], kind: 'narrative-ai', source: 'ai-narrative', description: 'ai rsk deviasi 3 mitigasi', anchor: 'RSK §I.3 — Deviasi RAC' },
  { name: 'ai_rsk_deviasi_4_mitigasi', templates: ['rsk'], kind: 'narrative-ai', source: 'ai-narrative', description: 'ai rsk deviasi 4 mitigasi', anchor: 'RSK §I.3 — Deviasi RAC' },
  // --- RSK §II.4 — Grup/Afiliasi ---
  { name: 'rsk_sister_company_1_nama', templates: ['rsk'], kind: 'fact-display', source: 'analyst', description: 'rsk sister company 1 nama', anchor: 'RSK §II.4 — Grup/Afiliasi' },
  { name: 'rsk_sister_company_1_bidang_usaha', templates: ['rsk'], kind: 'fact-display', source: 'analyst', description: 'rsk sister company 1 bidang usaha', anchor: 'RSK §II.4 — Grup/Afiliasi' },
  { name: 'rsk_sister_company_1_pembiayaan_or', templates: ['rsk'], kind: 'categorical', source: 'analyst', description: 'rsk sister company 1 pembiayaan or', anchor: 'RSK §II.4 — Grup/Afiliasi', enum: ['Ya', 'Tidak'] },
  { name: 'rsk_sister_company_2_nama', templates: ['rsk'], kind: 'fact-display', source: 'analyst', description: 'rsk sister company 2 nama', anchor: 'RSK §II.4 — Grup/Afiliasi' },
  { name: 'rsk_sister_company_2_bidang_usaha', templates: ['rsk'], kind: 'fact-display', source: 'analyst', description: 'rsk sister company 2 bidang usaha', anchor: 'RSK §II.4 — Grup/Afiliasi' },
  { name: 'rsk_sister_company_2_pembiayaan_or', templates: ['rsk'], kind: 'categorical', source: 'analyst', description: 'rsk sister company 2 pembiayaan or', anchor: 'RSK §II.4 — Grup/Afiliasi', enum: ['Ya', 'Tidak'] },
  // --- RSK §III.1 — Facility overlay ---
  { name: 'rsk_entitas_induk_nama', templates: ['rsk'], kind: 'fact-display', source: 'analyst', description: 'rsk entitas induk nama', anchor: 'RSK §III.1 — Facility overlay' },
  { name: 'rsk_entitas_induk_bidang_usaha', templates: ['rsk'], kind: 'fact-display', source: 'analyst', description: 'rsk entitas induk bidang usaha', anchor: 'RSK §III.1 — Facility overlay' },
  { name: 'rsk_jenis_fasilitas_or', templates: ['rsk'], kind: 'categorical', source: 'analyst', description: 'rsk jenis fasilitas or', anchor: 'RSK §III.1 — Facility overlay', enum: ['Line Facility', 'Term Loan', 'Non-Revolving', 'Revolving'] },
  { name: 'rsk_plafond_rekomendasi', templates: ['rsk'], kind: 'fact-display', source: 'analyst', description: 'rsk plafond rekomendasi', anchor: 'RSK §III.1 — Facility overlay' },
  { name: 'rsk_plafond_rekomendasi_terbilang', templates: ['rsk'], kind: 'fact-display', source: 'analyst', description: 'rsk plafond rekomendasi terbilang', anchor: 'RSK §III.1 — Facility overlay' },
  { name: 'rsk_akad_rekomendasi_or', templates: ['rsk'], kind: 'categorical', source: 'analyst', description: 'rsk akad rekomendasi or', anchor: 'RSK §III.1 — Facility overlay', enum: ['Murabahah', 'Musyarakah', 'Ijarah', 'IMBT', 'Istishna', 'Salam'] },
  { name: 'ai_rsk_akad_perbedaan_alasan', templates: ['rsk'], kind: 'narrative-ai', source: 'ai-narrative', description: 'ai rsk akad perbedaan alasan', anchor: 'RSK §III.1 — Facility overlay' },
  // --- RSK §III.2 — Ref Dokumen ---
  { name: 'rsk_ref_data_pendukung_tanggal', templates: ['rsk'], kind: 'fact-display', source: 'analyst', description: 'rsk ref data pendukung tanggal', anchor: 'RSK §III.2 — Ref Dokumen' },
  { name: 'ai_rsk_ref_data_pendukung_ringkas', templates: ['rsk'], kind: 'narrative-ai', source: 'ai-narrative', description: 'ai rsk ref data pendukung ringkas', anchor: 'RSK §III.2 — Ref Dokumen' },
  // --- RSK §III.3-5 ---
  { name: 'rsk_bmpd_memo_internal_no', templates: ['rsk'], kind: 'fact-display', source: 'analyst', description: 'rsk bmpd memo internal no', anchor: 'RSK §III.3-5' },
  { name: 'ai_rsk_source_of_repayment', templates: ['rsk'], kind: 'narrative-ai', source: 'ai-narrative', description: 'ai rsk source of repayment', anchor: 'RSK §III.3-5' },
  // --- RSK §IV.1 — Agunan ---
  { name: 'rsk_agunan_property_1_alamat', templates: ['rsk'], kind: 'fact-display', source: 'analyst', description: 'rsk agunan property 1 alamat', anchor: 'RSK §IV.1 — Agunan' },
  { name: 'rsk_agunan_property_1_pemilik', templates: ['rsk'], kind: 'fact-display', source: 'analyst', description: 'rsk agunan property 1 pemilik', anchor: 'RSK §IV.1 — Agunan' },
  { name: 'rsk_agunan_property_1_nilai_pasar', templates: ['rsk'], kind: 'fact-display', source: 'analyst', description: 'rsk agunan property 1 nilai pasar', anchor: 'RSK §IV.1 — Agunan' },
  { name: 'rsk_agunan_property_1_haircut_persen', templates: ['rsk'], kind: 'fact-display', source: 'analyst', description: 'rsk agunan property 1 haircut persen', anchor: 'RSK §IV.1 — Agunan' },
  { name: 'rsk_agunan_property_1_nilai_likuidasi', templates: ['rsk'], kind: 'fact-display', source: 'analyst', description: 'rsk agunan property 1 nilai likuidasi', anchor: 'RSK §IV.1 — Agunan' },
  // --- RSK §IV.1-3 — Agunan/SCCR ---
  { name: 'rsk_agunan_cash_collateral_persen', templates: ['rsk'], kind: 'fact-display', source: 'analyst', description: 'rsk agunan cash collateral persen', anchor: 'RSK §IV.1-3 — Agunan/SCCR' },
  { name: 'rsk_agunan_cash_collateral_nilai', templates: ['rsk'], kind: 'fact-display', source: 'analyst', description: 'rsk agunan cash collateral nilai', anchor: 'RSK §IV.1-3 — Agunan/SCCR' },
  { name: 'rsk_agunan_cessie_pemilik', templates: ['rsk'], kind: 'fact-display', source: 'analyst', description: 'rsk agunan cessie pemilik', anchor: 'RSK §IV.1-3 — Agunan/SCCR' },
  { name: 'rsk_agunan_cessie_nilai_pasar', templates: ['rsk'], kind: 'fact-display', source: 'analyst', description: 'rsk agunan cessie nilai pasar', anchor: 'RSK §IV.1-3 — Agunan/SCCR' },
  { name: 'rsk_agunan_cessie_haircut_persen', templates: ['rsk'], kind: 'fact-display', source: 'analyst', description: 'rsk agunan cessie haircut persen', anchor: 'RSK §IV.1-3 — Agunan/SCCR' },
  { name: 'rsk_agunan_cessie_nilai_likuidasi', templates: ['rsk'], kind: 'fact-display', source: 'analyst', description: 'rsk agunan cessie nilai likuidasi', anchor: 'RSK §IV.1-3 — Agunan/SCCR' },
  { name: 'rsk_agunan_pg_pemilik', templates: ['rsk'], kind: 'fact-display', source: 'analyst', description: 'rsk agunan pg pemilik', anchor: 'RSK §IV.1-3 — Agunan/SCCR' },
  { name: 'rsk_agunan_pg_asset_list_ref', templates: ['rsk'], kind: 'fact-display', source: 'analyst', description: 'rsk agunan pg asset list ref', anchor: 'RSK §IV.1-3 — Agunan/SCCR' },
  { name: 'rsk_sccr_total_likuidasi_adjusted', templates: ['rsk'], kind: 'fact-display', source: 'analyst', description: 'rsk sccr total likuidasi adjusted', anchor: 'RSK §IV.1-3 — Agunan/SCCR' },
  { name: 'rsk_sccr_rasio_adjusted', templates: ['rsk'], kind: 'fact-calc', source: 'derived', description: 'rsk sccr rasio adjusted', anchor: 'RSK §IV.1-3 — Agunan/SCCR', formula: 'Calculated from related template values at fill time' },
  { name: 'rsk_sccr_status_kepatuhan_or', templates: ['rsk'], kind: 'categorical', source: 'analyst', description: 'rsk sccr status kepatuhan or', anchor: 'RSK §IV.1-3 — Agunan/SCCR', enum: ['Aktif', 'Sudah berakhir', 'Renewal', 'Berakhir – tidak diperpanjang'] },
  { name: 'ai_rsk_agunan_adjustments', templates: ['rsk'], kind: 'narrative-ai', source: 'ai-narrative', description: 'ai rsk agunan adjustments', anchor: 'RSK §IV.1-3 — Agunan/SCCR' },
  // --- RSK §IV.4 — Red Flag Agunan ---
  { name: 'ai_rsk_red_flag_agunan_1_catatan', templates: ['rsk'], kind: 'narrative-ai', source: 'ai-narrative', description: 'ai rsk red flag agunan 1 catatan', anchor: 'RSK §IV.4 — Red Flag Agunan' },
  { name: 'rsk_red_flag_agunan_1_level_or', templates: ['rsk'], kind: 'categorical', source: 'analyst', description: 'rsk red flag agunan 1 level or', anchor: 'RSK §IV.4 — Red Flag Agunan', enum: ['RENDAH', 'SEDANG', 'TINGGI', 'KRITIS'] },
  { name: 'ai_rsk_red_flag_agunan_2_catatan', templates: ['rsk'], kind: 'narrative-ai', source: 'ai-narrative', description: 'ai rsk red flag agunan 2 catatan', anchor: 'RSK §IV.4 — Red Flag Agunan' },
  { name: 'rsk_red_flag_agunan_2_level_or', templates: ['rsk'], kind: 'categorical', source: 'analyst', description: 'rsk red flag agunan 2 level or', anchor: 'RSK §IV.4 — Red Flag Agunan', enum: ['RENDAH', 'SEDANG', 'TINGGI', 'KRITIS'] },
  { name: 'ai_rsk_red_flag_agunan_3_catatan', templates: ['rsk'], kind: 'narrative-ai', source: 'ai-narrative', description: 'ai rsk red flag agunan 3 catatan', anchor: 'RSK §IV.4 — Red Flag Agunan' },
  { name: 'rsk_red_flag_agunan_3_level_or', templates: ['rsk'], kind: 'categorical', source: 'analyst', description: 'rsk red flag agunan 3 level or', anchor: 'RSK §IV.4 — Red Flag Agunan', enum: ['RENDAH', 'SEDANG', 'TINGGI', 'KRITIS'] },
  // --- RSK §V.1 — Profil Bisnis ---
  { name: 'rsk_model_bisnis_ringkas', templates: ['rsk'], kind: 'fact-display', source: 'analyst', description: 'rsk model bisnis ringkas', anchor: 'RSK §V.1 — Profil Bisnis' },
  { name: 'rsk_client_bouwheer_utama_ringkas', templates: ['rsk'], kind: 'fact-display', source: 'analyst', description: 'rsk client bouwheer utama ringkas', anchor: 'RSK §V.1 — Profil Bisnis' },
  { name: 'rsk_ketergantungan_client_tunggal_or', templates: ['rsk'], kind: 'categorical', source: 'analyst', description: 'rsk ketergantungan client tunggal or', anchor: 'RSK §V.1 — Profil Bisnis', enum: ['Ya', 'Tidak'] },
  { name: 'rsk_persen_revenue_client_tunggal', templates: ['rsk'], kind: 'fact-display', source: 'analyst', description: 'rsk persen revenue client tunggal', anchor: 'RSK §V.1 — Profil Bisnis' },
  { name: 'rsk_pemasok_subkontraktor_ringkas', templates: ['rsk'], kind: 'fact-display', source: 'analyst', description: 'rsk pemasok subkontraktor ringkas', anchor: 'RSK §V.1 — Profil Bisnis' },
  { name: 'rsk_jumlah_karyawan_manajemen', templates: ['rsk'], kind: 'fact-display', source: 'analyst', description: 'rsk jumlah karyawan manajemen', anchor: 'RSK §V.1 — Profil Bisnis' },
  { name: 'rsk_jumlah_karyawan_operasional', templates: ['rsk'], kind: 'fact-display', source: 'analyst', description: 'rsk jumlah karyawan operasional', anchor: 'RSK §V.1 — Profil Bisnis' },
  { name: 'rsk_wilayah_operasional_ringkas', templates: ['rsk'], kind: 'fact-display', source: 'analyst', description: 'rsk wilayah operasional ringkas', anchor: 'RSK §V.1 — Profil Bisnis' },
  { name: 'rsk_sektor_industri_or', templates: ['rsk'], kind: 'categorical', source: 'analyst', description: 'rsk sektor industri or', anchor: 'RSK §V.1 — Profil Bisnis', enum: ['Ya', 'Tidak'] },
  { name: 'rsk_karakteristik_industri_ringkas', templates: ['rsk'], kind: 'fact-display', source: 'analyst', description: 'rsk karakteristik industri ringkas', anchor: 'RSK §V.1 — Profil Bisnis' },
  // --- RSK §V.2 — Kontrak Aktif ---
  { name: 'rsk_kontrak_aktif_1_status_or', templates: ['rsk'], kind: 'categorical', source: 'analyst', description: 'rsk kontrak aktif 1 status or', anchor: 'RSK §V.2 — Kontrak Aktif', enum: ['Aktif', 'Sudah berakhir', 'Renewal', 'Berakhir – tidak diperpanjang'] },
  { name: 'rsk_kontrak_aktif_2_status_or', templates: ['rsk'], kind: 'categorical', source: 'analyst', description: 'rsk kontrak aktif 2 status or', anchor: 'RSK §V.2 — Kontrak Aktif', enum: ['Aktif', 'Sudah berakhir', 'Renewal', 'Berakhir – tidak diperpanjang'] },
  { name: 'rsk_kontrak_aktif_3_status_or', templates: ['rsk'], kind: 'categorical', source: 'analyst', description: 'rsk kontrak aktif 3 status or', anchor: 'RSK §V.2 — Kontrak Aktif', enum: ['Aktif', 'Sudah berakhir', 'Renewal', 'Berakhir – tidak diperpanjang'] },
  { name: 'rsk_kontrak_aktif_4_status_or', templates: ['rsk'], kind: 'categorical', source: 'analyst', description: 'rsk kontrak aktif 4 status or', anchor: 'RSK §V.2 — Kontrak Aktif', enum: ['MEMENUHI', 'TIDAK MEMENUHI'] },
  // --- RSK §V.3 — Trade Checking ---
  { name: 'rsk_trade_check_1_client_cabang', templates: ['rsk'], kind: 'fact-display', source: 'analyst', description: 'rsk trade check 1 client cabang', anchor: 'RSK §V.3 — Trade Checking' },
  { name: 'rsk_trade_check_1_hasil_or', templates: ['rsk'], kind: 'categorical', source: 'analyst', description: 'rsk trade check 1 hasil or', anchor: 'RSK §V.3 — Trade Checking', enum: ['POSITIF', 'NEGATIF', 'TIDAK ADA RESPON'] },
  { name: 'ai_rsk_trade_check_1_keterangan', templates: ['rsk'], kind: 'narrative-ai', source: 'ai-narrative', description: 'ai rsk trade check 1 keterangan', anchor: 'RSK §V.3 — Trade Checking' },
  { name: 'rsk_trade_check_2_client_cabang', templates: ['rsk'], kind: 'fact-display', source: 'analyst', description: 'rsk trade check 2 client cabang', anchor: 'RSK §V.3 — Trade Checking' },
  { name: 'rsk_trade_check_2_hasil_or', templates: ['rsk'], kind: 'categorical', source: 'analyst', description: 'rsk trade check 2 hasil or', anchor: 'RSK §V.3 — Trade Checking', enum: ['POSITIF', 'NEGATIF', 'TIDAK ADA RESPON'] },
  { name: 'ai_rsk_trade_check_2_keterangan', templates: ['rsk'], kind: 'narrative-ai', source: 'ai-narrative', description: 'ai rsk trade check 2 keterangan', anchor: 'RSK §V.3 — Trade Checking' },
  // --- RSK §VI.1 — Financial Highlight ---
  { name: 'rsk_fin_highlight_laba_operasional_p1', templates: ['rsk'], kind: 'fact-display', source: 'analyst', description: 'rsk fin highlight laba operasional p1', anchor: 'RSK §VI.1 — Financial Highlight' },
  { name: 'rsk_fin_highlight_laba_operasional_p2', templates: ['rsk'], kind: 'fact-display', source: 'analyst', description: 'rsk fin highlight laba operasional p2', anchor: 'RSK §VI.1 — Financial Highlight' },
  { name: 'rsk_fin_highlight_laba_operasional_p3', templates: ['rsk'], kind: 'fact-display', source: 'analyst', description: 'rsk fin highlight laba operasional p3', anchor: 'RSK §VI.1 — Financial Highlight' },
  { name: 'ai_rsk_fin_highlight_pendapatan_catatan', templates: ['rsk'], kind: 'narrative-ai', source: 'ai-narrative', description: 'ai rsk fin highlight pendapatan catatan', anchor: 'RSK §VI.1 — Financial Highlight' },
  { name: 'ai_rsk_fin_highlight_yoy_catatan', templates: ['rsk'], kind: 'narrative-ai', source: 'ai-narrative', description: 'ai rsk fin highlight yoy catatan', anchor: 'RSK §VI.1 — Financial Highlight' },
  { name: 'ai_rsk_fin_highlight_gpm_catatan', templates: ['rsk'], kind: 'narrative-ai', source: 'ai-narrative', description: 'ai rsk fin highlight gpm catatan', anchor: 'RSK §VI.1 — Financial Highlight' },
  { name: 'ai_rsk_fin_highlight_cr_catatan', templates: ['rsk'], kind: 'narrative-ai', source: 'ai-narrative', description: 'ai rsk fin highlight cr catatan', anchor: 'RSK §VI.1 — Financial Highlight' },
  { name: 'ai_rsk_fin_highlight_der_catatan', templates: ['rsk'], kind: 'narrative-ai', source: 'ai-narrative', description: 'ai rsk fin highlight der catatan', anchor: 'RSK §VI.1 — Financial Highlight' },
  // --- RSK §VI.2 — Cashflow ---
  { name: 'rsk_cfo_2023', templates: ['rsk'], kind: 'fact-display', source: 'analyst', description: 'rsk cfo 2023', anchor: 'RSK §VI.2 — Cashflow' },
  { name: 'rsk_cfo_2024', templates: ['rsk'], kind: 'fact-display', source: 'analyst', description: 'rsk cfo 2024', anchor: 'RSK §VI.2 — Cashflow' },
  { name: 'rsk_cfo_periode_latest', templates: ['rsk'], kind: 'fact-display', source: 'analyst', description: 'rsk cfo periode latest', anchor: 'RSK §VI.2 — Cashflow' },
  { name: 'rsk_cfi_2023', templates: ['rsk'], kind: 'fact-display', source: 'analyst', description: 'rsk cfi 2023', anchor: 'RSK §VI.2 — Cashflow' },
  { name: 'rsk_cfi_2024', templates: ['rsk'], kind: 'fact-display', source: 'analyst', description: 'rsk cfi 2024', anchor: 'RSK §VI.2 — Cashflow' },
  { name: 'rsk_cfi_periode_latest', templates: ['rsk'], kind: 'fact-display', source: 'analyst', description: 'rsk cfi periode latest', anchor: 'RSK §VI.2 — Cashflow' },
  { name: 'rsk_cff_2023', templates: ['rsk'], kind: 'fact-display', source: 'analyst', description: 'rsk cff 2023', anchor: 'RSK §VI.2 — Cashflow' },
  { name: 'rsk_cff_2024', templates: ['rsk'], kind: 'fact-display', source: 'analyst', description: 'rsk cff 2024', anchor: 'RSK §VI.2 — Cashflow' },
  { name: 'rsk_cff_periode_latest', templates: ['rsk'], kind: 'fact-display', source: 'analyst', description: 'rsk cff periode latest', anchor: 'RSK §VI.2 — Cashflow' },
  { name: 'rsk_net_cf_2023', templates: ['rsk'], kind: 'fact-display', source: 'analyst', description: 'rsk net cf 2023', anchor: 'RSK §VI.2 — Cashflow' },
  { name: 'rsk_net_cf_2024', templates: ['rsk'], kind: 'fact-display', source: 'analyst', description: 'rsk net cf 2024', anchor: 'RSK §VI.2 — Cashflow' },
  { name: 'rsk_net_cf_periode_latest', templates: ['rsk'], kind: 'fact-display', source: 'analyst', description: 'rsk net cf periode latest', anchor: 'RSK §VI.2 — Cashflow' },
  { name: 'rsk_saldo_kas_akhir_2023', templates: ['rsk'], kind: 'fact-display', source: 'analyst', description: 'rsk saldo kas akhir 2023', anchor: 'RSK §VI.2 — Cashflow' },
  { name: 'rsk_saldo_kas_akhir_2024', templates: ['rsk'], kind: 'fact-display', source: 'analyst', description: 'rsk saldo kas akhir 2024', anchor: 'RSK §VI.2 — Cashflow' },
  { name: 'rsk_saldo_kas_akhir_periode_latest', templates: ['rsk'], kind: 'fact-display', source: 'analyst', description: 'rsk saldo kas akhir periode latest', anchor: 'RSK §VI.2 — Cashflow' },
  { name: 'ai_rsk_cfo_catatan', templates: ['rsk'], kind: 'narrative-ai', source: 'ai-narrative', description: 'ai rsk cfo catatan', anchor: 'RSK §VI.2 — Cashflow' },
  { name: 'ai_rsk_saldo_kas_verifikasi', templates: ['rsk'], kind: 'narrative-ai', source: 'ai-narrative', description: 'ai rsk saldo kas verifikasi', anchor: 'RSK §VI.2 — Cashflow' },
  // --- RSK §VI.3 — DSCRi ---
  { name: 'rsk_total_rab_proyek', templates: ['rsk'], kind: 'fact-display', source: 'analyst', description: 'rsk total rab proyek', anchor: 'RSK §VI.3 — DSCRi' },
  { name: 'rsk_total_rab_investasi', templates: ['rsk'], kind: 'fact-display', source: 'analyst', description: 'rsk total rab investasi', anchor: 'RSK §VI.3 — DSCRi' },
  { name: 'rsk_cfo_proyeksi_tahunan', templates: ['rsk'], kind: 'fact-display', source: 'analyst', description: 'rsk cfo proyeksi tahunan', anchor: 'RSK §VI.3 — DSCRi' },
  { name: 'rsk_total_kewajiban_tahunan', templates: ['rsk'], kind: 'fact-display', source: 'analyst', description: 'rsk total kewajiban tahunan', anchor: 'RSK §VI.3 — DSCRi' },
  { name: 'rsk_dscri_status_or', templates: ['rsk'], kind: 'categorical', source: 'analyst', description: 'rsk dscri status or', anchor: 'RSK §VI.3 — DSCRi', enum: ['AKTIF', 'MITIGATED', 'RENDAH', 'TINGGI'] },
  { name: 'rsk_plafond_mk_rekomendasi', templates: ['rsk'], kind: 'fact-display', source: 'analyst', description: 'rsk plafond mk rekomendasi', anchor: 'RSK §VI.3 — DSCRi' },
  { name: 'rsk_plafond_investasi_rekomendasi_or_pending', templates: ['rsk'], kind: 'categorical', source: 'analyst', description: 'rsk plafond investasi rekomendasi or pending', anchor: 'RSK §VI.3 — DSCRi', enum: ['Nominal', 'Pending', 'Ditunda'] },
  // --- RSK §VI.4 — Revenue Stream ---
  { name: 'rsk_revenue_1_nama', templates: ['rsk'], kind: 'fact-display', source: 'analyst', description: 'rsk revenue 1 nama', anchor: 'RSK §VI.4 — Revenue Stream' },
  { name: 'rsk_revenue_1_latest_rp', templates: ['rsk'], kind: 'fact-display', source: 'analyst', description: 'rsk revenue 1 latest rp', anchor: 'RSK §VI.4 — Revenue Stream' },
  { name: 'rsk_revenue_1_latest_pct', templates: ['rsk'], kind: 'fact-display', source: 'analyst', description: 'rsk revenue 1 latest pct', anchor: 'RSK §VI.4 — Revenue Stream' },
  { name: 'rsk_revenue_2_nama', templates: ['rsk'], kind: 'fact-display', source: 'analyst', description: 'rsk revenue 2 nama', anchor: 'RSK §VI.4 — Revenue Stream' },
  { name: 'rsk_revenue_2_latest_rp', templates: ['rsk'], kind: 'fact-display', source: 'analyst', description: 'rsk revenue 2 latest rp', anchor: 'RSK §VI.4 — Revenue Stream' },
  { name: 'rsk_revenue_2_latest_pct', templates: ['rsk'], kind: 'fact-display', source: 'analyst', description: 'rsk revenue 2 latest pct', anchor: 'RSK §VI.4 — Revenue Stream' },
  { name: 'rsk_revenue_total_2023_rp', templates: ['rsk'], kind: 'fact-calc', source: 'derived', description: 'rsk revenue total 2023 rp', anchor: 'RSK §VI.4 — Revenue Stream', formula: 'Calculated from related template values at fill time' },
  { name: 'rsk_revenue_total_2024_rp', templates: ['rsk'], kind: 'fact-calc', source: 'derived', description: 'rsk revenue total 2024 rp', anchor: 'RSK §VI.4 — Revenue Stream', formula: 'Calculated from related template values at fill time' },
  { name: 'rsk_revenue_total_latest_rp', templates: ['rsk'], kind: 'fact-calc', source: 'derived', description: 'rsk revenue total latest rp', anchor: 'RSK §VI.4 — Revenue Stream', formula: 'Calculated from related template values at fill time' },
  { name: 'ai_rsk_revenue_konsentrasi_catatan', templates: ['rsk'], kind: 'narrative-ai', source: 'ai-narrative', description: 'ai rsk revenue konsentrasi catatan', anchor: 'RSK §VI.4 — Revenue Stream' },
  // --- RSK §VII — 5C+2S ---
  { name: 'ai_rsk_5c_character_temuan', templates: ['rsk'], kind: 'narrative-ai', source: 'ai-narrative', description: 'ai rsk 5c character temuan', anchor: 'RSK §VII — 5C+2S' },
  { name: 'rsk_5c_character_level_or', templates: ['rsk'], kind: 'categorical', source: 'analyst', description: 'rsk 5c character level or', anchor: 'RSK §VII — 5C+2S', enum: ['RENDAH', 'SEDANG', 'TINGGI', 'KRITIS'] },
  { name: 'ai_rsk_5c_character_mitigasi', templates: ['rsk'], kind: 'narrative-ai', source: 'ai-narrative', description: 'ai rsk 5c character mitigasi', anchor: 'RSK §VII — 5C+2S' },
  { name: 'ai_rsk_5c_capacity_temuan', templates: ['rsk'], kind: 'narrative-ai', source: 'ai-narrative', description: 'ai rsk 5c capacity temuan', anchor: 'RSK §VII — 5C+2S' },
  { name: 'rsk_5c_capacity_level_or', templates: ['rsk'], kind: 'categorical', source: 'analyst', description: 'rsk 5c capacity level or', anchor: 'RSK §VII — 5C+2S', enum: ['RENDAH', 'SEDANG', 'TINGGI', 'KRITIS'] },
  { name: 'ai_rsk_5c_capacity_mitigasi', templates: ['rsk'], kind: 'narrative-ai', source: 'ai-narrative', description: 'ai rsk 5c capacity mitigasi', anchor: 'RSK §VII — 5C+2S' },
  { name: 'ai_rsk_5c_capital_temuan', templates: ['rsk'], kind: 'narrative-ai', source: 'ai-narrative', description: 'ai rsk 5c capital temuan', anchor: 'RSK §VII — 5C+2S' },
  { name: 'rsk_5c_capital_level_or', templates: ['rsk'], kind: 'categorical', source: 'analyst', description: 'rsk 5c capital level or', anchor: 'RSK §VII — 5C+2S', enum: ['RENDAH', 'SEDANG', 'TINGGI', 'KRITIS'] },
  { name: 'ai_rsk_5c_capital_mitigasi', templates: ['rsk'], kind: 'narrative-ai', source: 'ai-narrative', description: 'ai rsk 5c capital mitigasi', anchor: 'RSK §VII — 5C+2S' },
  { name: 'ai_rsk_5c_collateral_temuan', templates: ['rsk'], kind: 'narrative-ai', source: 'ai-narrative', description: 'ai rsk 5c collateral temuan', anchor: 'RSK §VII — 5C+2S' },
  { name: 'rsk_5c_collateral_level_or', templates: ['rsk'], kind: 'categorical', source: 'analyst', description: 'rsk 5c collateral level or', anchor: 'RSK §VII — 5C+2S', enum: ['RENDAH', 'SEDANG', 'TINGGI', 'KRITIS'] },
  { name: 'ai_rsk_5c_collateral_mitigasi', templates: ['rsk'], kind: 'narrative-ai', source: 'ai-narrative', description: 'ai rsk 5c collateral mitigasi', anchor: 'RSK §VII — 5C+2S' },
  { name: 'ai_rsk_5c_condition_temuan', templates: ['rsk'], kind: 'narrative-ai', source: 'ai-narrative', description: 'ai rsk 5c condition temuan', anchor: 'RSK §VII — 5C+2S' },
  { name: 'rsk_5c_condition_level_or', templates: ['rsk'], kind: 'categorical', source: 'analyst', description: 'rsk 5c condition level or', anchor: 'RSK §VII — 5C+2S', enum: ['RENDAH', 'SEDANG', 'TINGGI', 'KRITIS'] },
  { name: 'ai_rsk_5c_condition_mitigasi', templates: ['rsk'], kind: 'narrative-ai', source: 'ai-narrative', description: 'ai rsk 5c condition mitigasi', anchor: 'RSK §VII — 5C+2S' },
  { name: 'ai_rsk_5c_sharia_compliance_temuan', templates: ['rsk'], kind: 'narrative-ai', source: 'ai-narrative', description: 'ai rsk 5c sharia compliance temuan', anchor: 'RSK §VII — 5C+2S' },
  { name: 'rsk_5c_sharia_compliance_level_or', templates: ['rsk'], kind: 'categorical', source: 'analyst', description: 'rsk 5c sharia compliance level or', anchor: 'RSK §VII — 5C+2S', enum: ['RENDAH', 'SEDANG', 'TINGGI', 'KRITIS'] },
  { name: 'ai_rsk_5c_sharia_compliance_mitigasi', templates: ['rsk'], kind: 'narrative-ai', source: 'ai-narrative', description: 'ai rsk 5c sharia compliance mitigasi', anchor: 'RSK §VII — 5C+2S' },
  { name: 'ai_rsk_5c_sharia_structuring_temuan', templates: ['rsk'], kind: 'narrative-ai', source: 'ai-narrative', description: 'ai rsk 5c sharia structuring temuan', anchor: 'RSK §VII — 5C+2S' },
  { name: 'rsk_5c_sharia_structuring_level_or', templates: ['rsk'], kind: 'categorical', source: 'analyst', description: 'rsk 5c sharia structuring level or', anchor: 'RSK §VII — 5C+2S', enum: ['RENDAH', 'SEDANG', 'TINGGI', 'KRITIS'] },
  { name: 'ai_rsk_5c_sharia_structuring_mitigasi', templates: ['rsk'], kind: 'narrative-ai', source: 'ai-narrative', description: 'ai rsk 5c sharia structuring mitigasi', anchor: 'RSK §VII — 5C+2S' },
  // --- RSK §VII/VIII ---
  { name: 'rsk_5c_overall_level_or', templates: ['rsk'], kind: 'categorical', source: 'analyst', description: 'rsk 5c overall level or', anchor: 'RSK §VII/VIII', enum: ['RENDAH', 'SEDANG', 'TINGGI', 'KRITIS'] },
  { name: 'ai_rsk_5c_overall_summary', templates: ['rsk'], kind: 'narrative-ai', source: 'ai-narrative', description: 'ai rsk 5c overall summary', anchor: 'RSK §VII/VIII' },
  { name: 'ai_rsk_keputusan_qualifier', templates: ['rsk'], kind: 'narrative-ai', source: 'ai-narrative', description: 'ai rsk keputusan qualifier', anchor: 'RSK §VII/VIII' },
  // --- RSK §VIII.2 — CP ---
  { name: 'ai_rsk_cp_1_syarat', templates: ['rsk'], kind: 'narrative-ai', source: 'ai-narrative', description: 'ai rsk cp 1 syarat', anchor: 'RSK §VIII.2 — CP' },
  { name: 'rsk_cp_1_batas_waktu_or', templates: ['rsk'], kind: 'categorical', source: 'analyst', description: 'rsk cp 1 batas waktu or', anchor: 'RSK §VIII.2 — CP', enum: ['Sebelum akad', 'Sebelum pencairan pertama', 'Max bulan pasca akad'] },
  { name: 'rsk_cp_1_pic_or', templates: ['rsk'], kind: 'categorical', source: 'analyst', description: 'rsk cp 1 pic or', anchor: 'RSK §VIII.2 — CP', enum: ['Unit Bisnis', 'Legal', 'Risk', 'Nasabah'] },
  { name: 'ai_rsk_cp_2_syarat', templates: ['rsk'], kind: 'narrative-ai', source: 'ai-narrative', description: 'ai rsk cp 2 syarat', anchor: 'RSK §VIII.2 — CP' },
  { name: 'rsk_cp_2_batas_waktu_or', templates: ['rsk'], kind: 'categorical', source: 'analyst', description: 'rsk cp 2 batas waktu or', anchor: 'RSK §VIII.2 — CP', enum: ['Sebelum akad', 'Sebelum pencairan pertama', 'Max bulan pasca akad'] },
  { name: 'rsk_cp_2_pic_or', templates: ['rsk'], kind: 'categorical', source: 'analyst', description: 'rsk cp 2 pic or', anchor: 'RSK §VIII.2 — CP', enum: ['Unit Bisnis', 'Legal', 'Risk', 'Nasabah'] },
  { name: 'ai_rsk_cp_3_syarat', templates: ['rsk'], kind: 'narrative-ai', source: 'ai-narrative', description: 'ai rsk cp 3 syarat', anchor: 'RSK §VIII.2 — CP' },
  { name: 'rsk_cp_3_batas_waktu_or', templates: ['rsk'], kind: 'categorical', source: 'analyst', description: 'rsk cp 3 batas waktu or', anchor: 'RSK §VIII.2 — CP', enum: ['Sebelum akad', 'Sebelum pencairan pertama', 'Max bulan pasca akad'] },
  { name: 'rsk_cp_3_pic_or', templates: ['rsk'], kind: 'categorical', source: 'analyst', description: 'rsk cp 3 pic or', anchor: 'RSK §VIII.2 — CP', enum: ['Unit Bisnis', 'Legal', 'Risk', 'Nasabah'] },
  { name: 'ai_rsk_cp_4_syarat', templates: ['rsk'], kind: 'narrative-ai', source: 'ai-narrative', description: 'ai rsk cp 4 syarat', anchor: 'RSK §VIII.2 — CP' },
  { name: 'rsk_cp_4_batas_waktu_or', templates: ['rsk'], kind: 'categorical', source: 'analyst', description: 'rsk cp 4 batas waktu or', anchor: 'RSK §VIII.2 — CP', enum: ['Sebelum akad', 'Sebelum pencairan pertama', 'Max bulan pasca akad'] },
  { name: 'rsk_cp_4_pic_or', templates: ['rsk'], kind: 'categorical', source: 'analyst', description: 'rsk cp 4 pic or', anchor: 'RSK §VIII.2 — CP', enum: ['Unit Bisnis', 'Legal', 'Risk', 'Nasabah'] },
  { name: 'ai_rsk_cp_5_syarat', templates: ['rsk'], kind: 'narrative-ai', source: 'ai-narrative', description: 'ai rsk cp 5 syarat', anchor: 'RSK §VIII.2 — CP' },
  { name: 'rsk_cp_5_batas_waktu_or', templates: ['rsk'], kind: 'categorical', source: 'analyst', description: 'rsk cp 5 batas waktu or', anchor: 'RSK §VIII.2 — CP', enum: ['Sebelum akad', 'Sebelum pencairan pertama', 'Max bulan pasca akad'] },
  { name: 'rsk_cp_5_pic_or', templates: ['rsk'], kind: 'categorical', source: 'analyst', description: 'rsk cp 5 pic or', anchor: 'RSK §VIII.2 — CP', enum: ['Unit Bisnis', 'Legal', 'Risk', 'Nasabah'] },
  // --- RSK §VIII.3 — Covenant ---
  { name: 'ai_rsk_covenant_1_text', templates: ['rsk'], kind: 'narrative-ai', source: 'ai-narrative', description: 'ai rsk covenant 1 text', anchor: 'RSK §VIII.3 — Covenant' },
  { name: 'ai_rsk_covenant_1_konsekuensi', templates: ['rsk'], kind: 'narrative-ai', source: 'ai-narrative', description: 'ai rsk covenant 1 konsekuensi', anchor: 'RSK §VIII.3 — Covenant' },
  { name: 'ai_rsk_covenant_2_text', templates: ['rsk'], kind: 'narrative-ai', source: 'ai-narrative', description: 'ai rsk covenant 2 text', anchor: 'RSK §VIII.3 — Covenant' },
  { name: 'ai_rsk_covenant_2_konsekuensi', templates: ['rsk'], kind: 'narrative-ai', source: 'ai-narrative', description: 'ai rsk covenant 2 konsekuensi', anchor: 'RSK §VIII.3 — Covenant' },
  // --- RSK §VIII.4 — Monitoring ---
  { name: 'rsk_monitoring_1_aktivitas_or', templates: ['rsk'], kind: 'categorical', source: 'analyst', description: 'rsk monitoring 1 aktivitas or', anchor: 'RSK §VIII.4 — Monitoring', enum: ['Review Keuangan', 'Trade Checking Client', 'Kunjungan On-site', 'Monitoring SLIK', 'Verifikasi Underlying', 'Monitoring Syariah', 'Review Status Balik Nama Agunan', 'Lainnya'] },
  { name: 'rsk_monitoring_1_frekuensi_or', templates: ['rsk'], kind: 'categorical', source: 'analyst', description: 'rsk monitoring 1 frekuensi or', anchor: 'RSK §VIII.4 — Monitoring', enum: ['Setiap 3 bulan', 'Setiap 6 bulan', 'Minimal 1x per semester', 'Setiap tahun', 'Setiap penarikan', 'Lainnya'] },
  { name: 'ai_rsk_monitoring_1_item', templates: ['rsk'], kind: 'narrative-ai', source: 'ai-narrative', description: 'ai rsk monitoring 1 item', anchor: 'RSK §VIII.4 — Monitoring' },
  { name: 'rsk_monitoring_2_aktivitas_or', templates: ['rsk'], kind: 'categorical', source: 'analyst', description: 'rsk monitoring 2 aktivitas or', anchor: 'RSK §VIII.4 — Monitoring', enum: ['Review Keuangan', 'Trade Checking Client', 'Kunjungan On-site', 'Monitoring SLIK', 'Verifikasi Underlying', 'Monitoring Syariah', 'Review Status Balik Nama Agunan', 'Lainnya'] },
  { name: 'rsk_monitoring_2_frekuensi_or', templates: ['rsk'], kind: 'categorical', source: 'analyst', description: 'rsk monitoring 2 frekuensi or', anchor: 'RSK §VIII.4 — Monitoring', enum: ['Setiap 3 bulan', 'Setiap 6 bulan', 'Minimal 1x per semester', 'Setiap tahun', 'Setiap penarikan', 'Lainnya'] },
  { name: 'ai_rsk_monitoring_2_item', templates: ['rsk'], kind: 'narrative-ai', source: 'ai-narrative', description: 'ai rsk monitoring 2 item', anchor: 'RSK §VIII.4 — Monitoring' },
  { name: 'rsk_monitoring_3_aktivitas_or', templates: ['rsk'], kind: 'categorical', source: 'analyst', description: 'rsk monitoring 3 aktivitas or', anchor: 'RSK §VIII.4 — Monitoring', enum: ['Review Keuangan', 'Trade Checking Client', 'Kunjungan On-site', 'Monitoring SLIK', 'Verifikasi Underlying', 'Monitoring Syariah', 'Review Status Balik Nama Agunan', 'Lainnya'] },
  { name: 'rsk_monitoring_3_frekuensi_or', templates: ['rsk'], kind: 'categorical', source: 'analyst', description: 'rsk monitoring 3 frekuensi or', anchor: 'RSK §VIII.4 — Monitoring', enum: ['Setiap 3 bulan', 'Setiap 6 bulan', 'Minimal 1x per semester', 'Setiap tahun', 'Setiap penarikan', 'Lainnya'] },
  { name: 'ai_rsk_monitoring_3_item', templates: ['rsk'], kind: 'narrative-ai', source: 'ai-narrative', description: 'ai rsk monitoring 3 item', anchor: 'RSK §VIII.4 — Monitoring' },
  { name: 'rsk_monitoring_4_aktivitas_or', templates: ['rsk'], kind: 'categorical', source: 'analyst', description: 'rsk monitoring 4 aktivitas or', anchor: 'RSK §VIII.4 — Monitoring', enum: ['Review Keuangan', 'Trade Checking Client', 'Kunjungan On-site', 'Monitoring SLIK', 'Verifikasi Underlying', 'Monitoring Syariah', 'Review Status Balik Nama Agunan', 'Lainnya'] },
  { name: 'rsk_monitoring_4_frekuensi_or', templates: ['rsk'], kind: 'categorical', source: 'analyst', description: 'rsk monitoring 4 frekuensi or', anchor: 'RSK §VIII.4 — Monitoring', enum: ['Setiap 3 bulan', 'Setiap 6 bulan', 'Minimal 1x per semester', 'Setiap tahun', 'Setiap penarikan', 'Lainnya'] },
  { name: 'ai_rsk_monitoring_4_item', templates: ['rsk'], kind: 'narrative-ai', source: 'ai-narrative', description: 'ai rsk monitoring 4 item', anchor: 'RSK §VIII.4 — Monitoring' },
  // --- RSK §VIII.5 — Red Flag ---
  { name: 'rsk_red_flag_1_kategori_or', templates: ['rsk'], kind: 'categorical', source: 'analyst', description: 'rsk red flag 1 kategori or', anchor: 'RSK §VIII.5 — Red Flag', enum: ['RED FLAG KEUANGAN', 'RED FLAG AGUNAN', 'RED FLAG BISNIS', 'RED FLAG SYARIAH', 'RED FLAG MANAJEMEN', 'RED FLAG LEGAL'] },
  { name: 'ai_rsk_red_flag_1_deskripsi', templates: ['rsk'], kind: 'narrative-ai', source: 'ai-narrative', description: 'ai rsk red flag 1 deskripsi', anchor: 'RSK §VIII.5 — Red Flag' },
  { name: 'rsk_red_flag_1_status_or', templates: ['rsk'], kind: 'categorical', source: 'analyst', description: 'rsk red flag 1 status or', anchor: 'RSK §VIII.5 — Red Flag', enum: ['AKTIF', 'MITIGATED', 'RENDAH', 'TINGGI'] },
  { name: 'rsk_red_flag_2_kategori_or', templates: ['rsk'], kind: 'categorical', source: 'analyst', description: 'rsk red flag 2 kategori or', anchor: 'RSK §VIII.5 — Red Flag', enum: ['RED FLAG KEUANGAN', 'RED FLAG AGUNAN', 'RED FLAG BISNIS', 'RED FLAG SYARIAH', 'RED FLAG MANAJEMEN', 'RED FLAG LEGAL'] },
  { name: 'ai_rsk_red_flag_2_deskripsi', templates: ['rsk'], kind: 'narrative-ai', source: 'ai-narrative', description: 'ai rsk red flag 2 deskripsi', anchor: 'RSK §VIII.5 — Red Flag' },
  { name: 'rsk_red_flag_2_status_or', templates: ['rsk'], kind: 'categorical', source: 'analyst', description: 'rsk red flag 2 status or', anchor: 'RSK §VIII.5 — Red Flag', enum: ['AKTIF', 'MITIGATED', 'RENDAH', 'TINGGI'] },
  { name: 'rsk_red_flag_3_kategori_or', templates: ['rsk'], kind: 'categorical', source: 'analyst', description: 'rsk red flag 3 kategori or', anchor: 'RSK §VIII.5 — Red Flag', enum: ['RED FLAG KEUANGAN', 'RED FLAG AGUNAN', 'RED FLAG BISNIS', 'RED FLAG SYARIAH', 'RED FLAG MANAJEMEN', 'RED FLAG LEGAL'] },
  { name: 'rsk_red_flag_3_status_or', templates: ['rsk'], kind: 'categorical', source: 'analyst', description: 'rsk red flag 3 status or', anchor: 'RSK §VIII.5 — Red Flag', enum: ['AKTIF', 'MITIGATED', 'RENDAH', 'TINGGI'] },
  // --- RSK §IX — Signatures ---
  { name: 'rsk_sig_analyst_nama', templates: ['rsk'], kind: 'fact-display', source: 'analyst', description: 'rsk sig analyst nama', anchor: 'RSK §IX — Signatures' },
  { name: 'rsk_sig_analyst_nik', templates: ['rsk'], kind: 'fact-display', source: 'analyst', description: 'rsk sig analyst nik', anchor: 'RSK §IX — Signatures' },
  { name: 'rsk_sig_analyst_tanggal', templates: ['rsk'], kind: 'fact-display', source: 'analyst', description: 'rsk sig analyst tanggal', anchor: 'RSK §IX — Signatures' },
  { name: 'rsk_sig_officer_nama', templates: ['rsk'], kind: 'fact-display', source: 'analyst', description: 'rsk sig officer nama', anchor: 'RSK §IX — Signatures' },
  { name: 'rsk_sig_officer_nik', templates: ['rsk'], kind: 'fact-display', source: 'analyst', description: 'rsk sig officer nik', anchor: 'RSK §IX — Signatures' },
  { name: 'rsk_sig_officer_tanggal', templates: ['rsk'], kind: 'fact-display', source: 'analyst', description: 'rsk sig officer tanggal', anchor: 'RSK §IX — Signatures' },
  { name: 'rsk_sig_cro_nama', templates: ['rsk'], kind: 'fact-display', source: 'analyst', description: 'rsk sig cro nama', anchor: 'RSK §IX — Signatures' },
  { name: 'rsk_sig_cro_nik', templates: ['rsk'], kind: 'fact-display', source: 'analyst', description: 'rsk sig cro nik', anchor: 'RSK §IX — Signatures' },
  { name: 'rsk_sig_cro_tanggal', templates: ['rsk'], kind: 'fact-display', source: 'analyst', description: 'rsk sig cro tanggal', anchor: 'RSK §IX — Signatures' },
  // --- RSK T33 — DPS ---
  { name: 'rsk_dps_akad_assessment_or', templates: ['rsk'], kind: 'categorical', source: 'analyst', description: 'rsk dps akad assessment or', anchor: 'RSK T33 — DPS', enum: ['SESUAI', 'PERLU_PENYESUAIAN'] },
  { name: 'ai_rsk_dps_akad_penyesuaian', templates: ['rsk'], kind: 'narrative-ai', source: 'ai-narrative', description: 'ai rsk dps akad penyesuaian', anchor: 'RSK T33 — DPS' },
  { name: 'rsk_dps_usaha_assessment_or', templates: ['rsk'], kind: 'categorical', source: 'analyst', description: 'rsk dps usaha assessment or', anchor: 'RSK T33 — DPS', enum: ['HALAL', 'PERLU_KLARIFIKASI'] },
  { name: 'ai_rsk_dps_catatan', templates: ['rsk'], kind: 'narrative-ai', source: 'ai-narrative', description: 'ai rsk dps catatan', anchor: 'RSK T33 — DPS' },
  { name: 'rsk_dps_nama', templates: ['rsk'], kind: 'fact-display', source: 'analyst', description: 'rsk dps nama', anchor: 'RSK T33 — DPS' },
  { name: 'rsk_dps_tanggal', templates: ['rsk'], kind: 'fact-display', source: 'analyst', description: 'rsk dps tanggal', anchor: 'RSK T33 — DPS' },
  // --- Master reconciliation (2026.06.04): rsk_* {{token}} literals in the live RSK master absent
  // from the registry. RSK-owned (rsk_ prefix) per AGENTS.md. Unblocks setup-v2-named-ranges --apply.
  { name: 'rsk_ref_muap_no_tanggal', templates: ['rsk'], kind: 'fact-display', source: 'analyst', description: 'rsk ref muap no tanggal', anchor: 'RSK ref (master)' },
  { name: 'rsk_ref_kontrak_utama_no_tanggal', templates: ['rsk'], kind: 'fact-display', source: 'analyst', description: 'rsk ref kontrak utama no tanggal', anchor: 'RSK ref (master)' },
  { name: 'rsk_agunan_property_2_alamat', templates: ['rsk'], kind: 'fact-display', source: 'analyst', description: 'rsk agunan property 2 alamat', anchor: 'RSK §IV.1 — Agunan (master)' },
  { name: 'rsk_agunan_property_2_pemilik', templates: ['rsk'], kind: 'fact-display', source: 'analyst', description: 'rsk agunan property 2 pemilik', anchor: 'RSK §IV.1 — Agunan (master)' },
  { name: 'rsk_agunan_property_2_nilai_pasar', templates: ['rsk'], kind: 'fact-display', source: 'analyst', description: 'rsk agunan property 2 nilai pasar', anchor: 'RSK §IV.1 — Agunan (master)' },
  { name: 'rsk_agunan_property_2_haircut_persen', templates: ['rsk'], kind: 'fact-display', source: 'analyst', description: 'rsk agunan property 2 haircut persen', anchor: 'RSK §IV.1 — Agunan (master)' },
  { name: 'rsk_agunan_property_2_nilai_likuidasi', templates: ['rsk'], kind: 'fact-display', source: 'analyst', description: 'rsk agunan property 2 nilai likuidasi', anchor: 'RSK §IV.1 — Agunan (master)' },
  { name: 'rsk_catatan_dps', templates: ['rsk'], kind: 'fact-display', source: 'analyst', description: 'rsk catatan dps', anchor: 'RSK T33 — DPS (master)' },
]
