/**
 * Shared MUAP/RSK tokens — legitimate R1 reuses after RSK rev 2 retargeting.
 */
import type { TemplateToken } from './types'

export const SHARED_TOKENS: ReadonlyArray<TemplateToken> = [
  // --- MUAP T2-T6 existing ---
  { name: 'nama_perusahaan', templates: ['muap', 'rsk'], kind: 'fact-display', source: 'app', description: 'nama perusahaan', anchor: 'MUAP T2-T6 existing' },
  { name: 'nama_grup_usaha', templates: ['muap', 'rsk'], kind: 'fact-display', source: 'app', description: 'nama grup usaha', anchor: 'MUAP T2-T6 existing' },
  { name: 'alamat_kantor_nib', templates: ['muap', 'rsk'], kind: 'fact-display', source: 'app', description: 'alamat kantor nib', anchor: 'MUAP T2-T6 existing' },
  { name: 'alamat_kantor_visit', templates: ['muap', 'rsk'], kind: 'fact-display', source: 'app', description: 'alamat kantor visit', anchor: 'MUAP T2-T6 existing' },
  { name: 'bidang_usaha_utama', templates: ['muap', 'rsk'], kind: 'fact-display', source: 'app', description: 'bidang usaha utama', anchor: 'MUAP T2-T6 existing' },
  { name: 'nasabah_baru_or_lama', templates: ['muap', 'rsk'], kind: 'categorical', source: 'app', description: 'nasabah baru or lama', anchor: 'MUAP T2-T6 existing', enum: ['Baru', 'Lama'] },
  { name: 'source_of_referral', templates: ['muap', 'rsk'], kind: 'fact-display', source: 'app', description: 'source of referral', anchor: 'MUAP T2-T6 existing' },
  { name: 'tanggal_menjadi_nasabah_or_strip', templates: ['muap', 'rsk'], kind: 'categorical', source: 'app', description: 'tanggal menjadi nasabah or strip', anchor: 'MUAP T2-T6 existing', enum: ['Tanggal', '-'] },
  { name: 'nama_lengkap_direktur', templates: ['muap', 'rsk'], kind: 'fact-display', source: 'app', description: 'nama lengkap direktur', anchor: 'MUAP T2-T6 existing' },
  { name: 'nama_lengkap_komisaris', templates: ['muap', 'rsk'], kind: 'fact-display', source: 'app', description: 'nama lengkap komisaris', anchor: 'MUAP T2-T6 existing' },
  { name: 'plafond', templates: ['muap', 'rsk'], kind: 'fact-display', source: 'app', description: 'plafond', anchor: 'MUAP T2-T6 existing' },
  { name: 'plafond_terbilang', templates: ['muap', 'rsk'], kind: 'fact-display', source: 'app', description: 'plafond terbilang', anchor: 'MUAP T2-T6 existing' },
  // --- MUAP T11-T18 existing ---
  { name: 'no_akta_pendirian', templates: ['muap', 'rsk'], kind: 'fact-display', source: 'app', description: 'no akta pendirian', anchor: 'MUAP T11-T18 existing' },
  { name: 'tanggal_akta_pendirian', templates: ['muap', 'rsk'], kind: 'fact-display', source: 'app', description: 'tanggal akta pendirian', anchor: 'MUAP T11-T18 existing' },
  { name: 'notaris_akta_pendirian', templates: ['muap', 'rsk'], kind: 'fact-display', source: 'app', description: 'notaris akta pendirian', anchor: 'MUAP T11-T18 existing' },
  { name: 'no_nib', templates: ['muap', 'rsk'], kind: 'fact-display', source: 'app', description: 'no nib', anchor: 'MUAP T11-T18 existing' },
  { name: 'no_npwp', templates: ['muap', 'rsk'], kind: 'fact-display', source: 'app', description: 'no npwp', anchor: 'MUAP T11-T18 existing' },
  { name: 'izin_usaha_sektoral', templates: ['muap', 'rsk'], kind: 'fact-display', source: 'app', description: 'izin usaha sektoral', anchor: 'MUAP T11-T18 existing' },
  { name: 'izin_usaha_sektoral_berlaku_sampai', templates: ['muap', 'rsk'], kind: 'fact-display', source: 'app', description: 'izin usaha sektoral berlaku sampai', anchor: 'MUAP T11-T18 existing' },
  { name: 'no_kbli', templates: ['muap', 'rsk'], kind: 'fact-display', source: 'app', description: 'no kbli', anchor: 'MUAP T11-T18 existing' },
  { name: 'deskripsi_kbli', templates: ['muap', 'rsk'], kind: 'fact-display', source: 'app', description: 'deskripsi kbli', anchor: 'MUAP T11-T18 existing' },
  { name: 'persen_direktur', templates: ['muap', 'rsk'], kind: 'fact-display', source: 'app', description: 'persen direktur', anchor: 'MUAP T11-T18 existing' },
  { name: 'professional_or_keluarga_direktur', templates: ['muap', 'rsk'], kind: 'categorical', source: 'app', description: 'professional or keluarga direktur', anchor: 'MUAP T11-T18 existing', enum: ['Professional', 'Keluarga'] },
  { name: 'persen_komisaris', templates: ['muap', 'rsk'], kind: 'fact-display', source: 'app', description: 'persen komisaris', anchor: 'MUAP T11-T18 existing' },
  { name: 'professional_or_keluarga_komisaris', templates: ['muap', 'rsk'], kind: 'categorical', source: 'app', description: 'professional or keluarga komisaris', anchor: 'MUAP T11-T18 existing', enum: ['Professional', 'Keluarga'] },
  { name: 'ai_keterangan_key_person_direktur', templates: ['muap', 'rsk'], kind: 'narrative-ai', source: 'ai-with-research-context', description: 'ai keterangan key person direktur', anchor: 'MUAP T11-T18 existing' },
  { name: 'ai_keterangan_key_person_komisaris', templates: ['muap', 'rsk'], kind: 'narrative-ai', source: 'ai-with-research-context', description: 'ai keterangan key person komisaris', anchor: 'MUAP T11-T18 existing' },
  // --- MUAP T21 — Detail SLIK OJK ---
  { name: 'kol_slik_pemohon', templates: ['muap', 'rsk'], kind: 'fact-display', source: 'app', description: 'kol slik pemohon', anchor: 'MUAP T21 — Detail SLIK OJK' },
  { name: 'baki_debet_slik_pemohon', templates: ['muap', 'rsk'], kind: 'fact-display', source: 'app', description: 'baki debet slik pemohon', anchor: 'MUAP T21 — Detail SLIK OJK' },
  { name: 'bank_slik_pemohon', templates: ['muap', 'rsk'], kind: 'fact-display', source: 'app', description: 'bank slik pemohon', anchor: 'MUAP T21 — Detail SLIK OJK' },
  { name: 'ai_keterangan_slik_pemohon', templates: ['muap', 'rsk'], kind: 'narrative-ai', source: 'ai-with-research-context', description: 'ai keterangan slik pemohon', anchor: 'MUAP T21 — Detail SLIK OJK' },
  { name: 'kol_slik_direktur', templates: ['muap', 'rsk'], kind: 'fact-display', source: 'app', description: 'kol slik direktur', anchor: 'MUAP T21 — Detail SLIK OJK' },
  { name: 'baki_debet_slik_direktur', templates: ['muap', 'rsk'], kind: 'fact-display', source: 'app', description: 'baki debet slik direktur', anchor: 'MUAP T21 — Detail SLIK OJK' },
  { name: 'bank_slik_direktur', templates: ['muap', 'rsk'], kind: 'fact-display', source: 'app', description: 'bank slik direktur', anchor: 'MUAP T21 — Detail SLIK OJK' },
  { name: 'ai_keterangan_slik_direktur', templates: ['muap', 'rsk'], kind: 'narrative-ai', source: 'ai-with-research-context', description: 'ai keterangan slik direktur', anchor: 'MUAP T21 — Detail SLIK OJK' },
  { name: 'kol_slik_komisaris', templates: ['muap', 'rsk'], kind: 'fact-display', source: 'app', description: 'kol slik komisaris', anchor: 'MUAP T21 — Detail SLIK OJK' },
  { name: 'baki_debet_slik_komisaris', templates: ['muap', 'rsk'], kind: 'fact-display', source: 'app', description: 'baki debet slik komisaris', anchor: 'MUAP T21 — Detail SLIK OJK' },
  { name: 'bank_slik_komisaris', templates: ['muap', 'rsk'], kind: 'fact-display', source: 'app', description: 'bank slik komisaris', anchor: 'MUAP T21 — Detail SLIK OJK' },
  { name: 'ai_keterangan_slik_komisaris', templates: ['muap', 'rsk'], kind: 'narrative-ai', source: 'ai-with-research-context', description: 'ai keterangan slik komisaris', anchor: 'MUAP T21 — Detail SLIK OJK' },
  // --- MUAP T29 — Lokasi & Visit ---
  { name: 'ai_kunjungan_lapangan_catatan', templates: ['muap', 'rsk'], kind: 'narrative-ai', source: 'ai-with-research-context', description: 'ai kunjungan lapangan catatan', anchor: 'MUAP T29 — Lokasi & Visit' },
  // --- MUAP T36 — Progress Pipeline ---
  { name: 'bouwheer_pipeline_1', templates: ['muap', 'rsk'], kind: 'fact-display', source: 'app', description: 'bouwheer pipeline 1', anchor: 'MUAP T36 — Progress Pipeline' },
  { name: 'nama_pekerjaan_pipeline_1', templates: ['muap', 'rsk'], kind: 'fact-display', source: 'app', description: 'nama pekerjaan pipeline 1', anchor: 'MUAP T36 — Progress Pipeline' },
  { name: 'nilai_pekerjaan_pipeline_1', templates: ['muap', 'rsk'], kind: 'fact-display', source: 'app', description: 'nilai pekerjaan pipeline 1', anchor: 'MUAP T36 — Progress Pipeline' },
  { name: 'periode_pekerjaan_pipeline_1', templates: ['muap', 'rsk'], kind: 'fact-display', source: 'app', description: 'periode pekerjaan pipeline 1', anchor: 'MUAP T36 — Progress Pipeline' },
  { name: 'bouwheer_pipeline_2', templates: ['muap', 'rsk'], kind: 'fact-display', source: 'app', description: 'bouwheer pipeline 2', anchor: 'MUAP T36 — Progress Pipeline' },
  { name: 'nama_pekerjaan_pipeline_2', templates: ['muap', 'rsk'], kind: 'fact-display', source: 'app', description: 'nama pekerjaan pipeline 2', anchor: 'MUAP T36 — Progress Pipeline' },
  { name: 'nilai_pekerjaan_pipeline_2', templates: ['muap', 'rsk'], kind: 'fact-display', source: 'app', description: 'nilai pekerjaan pipeline 2', anchor: 'MUAP T36 — Progress Pipeline' },
  { name: 'periode_pekerjaan_pipeline_2', templates: ['muap', 'rsk'], kind: 'fact-display', source: 'app', description: 'periode pekerjaan pipeline 2', anchor: 'MUAP T36 — Progress Pipeline' },
  // --- MUAP T43 — Laba Rugi ---
  { name: 'laba_rugi_pendapatan_p1', templates: ['muap', 'rsk'], kind: 'fact-display', source: 'app', description: 'laba rugi pendapatan p1', anchor: 'MUAP T43 — Laba Rugi' },
  { name: 'laba_rugi_hpp_p1', templates: ['muap', 'rsk'], kind: 'fact-display', source: 'app', description: 'laba rugi hpp p1', anchor: 'MUAP T43 — Laba Rugi' },
  { name: 'laba_rugi_gross_profit_p1', templates: ['muap', 'rsk'], kind: 'fact-display', source: 'app', description: 'laba rugi gross profit p1', anchor: 'MUAP T43 — Laba Rugi' },
  { name: 'laba_rugi_gpm_p1', templates: ['muap', 'rsk'], kind: 'fact-display', source: 'app', description: 'laba rugi gpm p1', anchor: 'MUAP T43 — Laba Rugi' },
  { name: 'laba_rugi_biaya_operasional_p1', templates: ['muap', 'rsk'], kind: 'fact-display', source: 'app', description: 'laba rugi biaya operasional p1', anchor: 'MUAP T43 — Laba Rugi' },
  { name: 'laba_rugi_ebitda_p1', templates: ['muap', 'rsk'], kind: 'fact-display', source: 'app', description: 'laba rugi ebitda p1', anchor: 'MUAP T43 — Laba Rugi' },
  { name: 'laba_rugi_net_profit_p1', templates: ['muap', 'rsk'], kind: 'fact-display', source: 'app', description: 'laba rugi net profit p1', anchor: 'MUAP T43 — Laba Rugi' },
  { name: 'laba_rugi_npm_p1', templates: ['muap', 'rsk'], kind: 'fact-display', source: 'app', description: 'laba rugi npm p1', anchor: 'MUAP T43 — Laba Rugi' },
  { name: 'laba_rugi_pendapatan_p2', templates: ['muap', 'rsk'], kind: 'fact-display', source: 'app', description: 'laba rugi pendapatan p2', anchor: 'MUAP T43 — Laba Rugi' },
  { name: 'laba_rugi_hpp_p2', templates: ['muap', 'rsk'], kind: 'fact-display', source: 'app', description: 'laba rugi hpp p2', anchor: 'MUAP T43 — Laba Rugi' },
  { name: 'laba_rugi_gross_profit_p2', templates: ['muap', 'rsk'], kind: 'fact-display', source: 'app', description: 'laba rugi gross profit p2', anchor: 'MUAP T43 — Laba Rugi' },
  { name: 'laba_rugi_gpm_p2', templates: ['muap', 'rsk'], kind: 'fact-display', source: 'app', description: 'laba rugi gpm p2', anchor: 'MUAP T43 — Laba Rugi' },
  { name: 'laba_rugi_biaya_operasional_p2', templates: ['muap', 'rsk'], kind: 'fact-display', source: 'app', description: 'laba rugi biaya operasional p2', anchor: 'MUAP T43 — Laba Rugi' },
  { name: 'laba_rugi_ebitda_p2', templates: ['muap', 'rsk'], kind: 'fact-display', source: 'app', description: 'laba rugi ebitda p2', anchor: 'MUAP T43 — Laba Rugi' },
  { name: 'laba_rugi_net_profit_p2', templates: ['muap', 'rsk'], kind: 'fact-display', source: 'app', description: 'laba rugi net profit p2', anchor: 'MUAP T43 — Laba Rugi' },
  { name: 'laba_rugi_npm_p2', templates: ['muap', 'rsk'], kind: 'fact-display', source: 'app', description: 'laba rugi npm p2', anchor: 'MUAP T43 — Laba Rugi' },
  { name: 'laba_rugi_pendapatan_p3', templates: ['muap', 'rsk'], kind: 'fact-display', source: 'app', description: 'laba rugi pendapatan p3', anchor: 'MUAP T43 — Laba Rugi' },
  { name: 'laba_rugi_hpp_p3', templates: ['muap', 'rsk'], kind: 'fact-display', source: 'app', description: 'laba rugi hpp p3', anchor: 'MUAP T43 — Laba Rugi' },
  { name: 'laba_rugi_gross_profit_p3', templates: ['muap', 'rsk'], kind: 'fact-display', source: 'app', description: 'laba rugi gross profit p3', anchor: 'MUAP T43 — Laba Rugi' },
  { name: 'laba_rugi_gpm_p3', templates: ['muap', 'rsk'], kind: 'fact-display', source: 'app', description: 'laba rugi gpm p3', anchor: 'MUAP T43 — Laba Rugi' },
  { name: 'laba_rugi_biaya_operasional_p3', templates: ['muap', 'rsk'], kind: 'fact-display', source: 'app', description: 'laba rugi biaya operasional p3', anchor: 'MUAP T43 — Laba Rugi' },
  { name: 'laba_rugi_ebitda_p3', templates: ['muap', 'rsk'], kind: 'fact-display', source: 'app', description: 'laba rugi ebitda p3', anchor: 'MUAP T43 — Laba Rugi' },
  { name: 'laba_rugi_net_profit_p3', templates: ['muap', 'rsk'], kind: 'fact-display', source: 'app', description: 'laba rugi net profit p3', anchor: 'MUAP T43 — Laba Rugi' },
  { name: 'laba_rugi_npm_p3', templates: ['muap', 'rsk'], kind: 'fact-display', source: 'app', description: 'laba rugi npm p3', anchor: 'MUAP T43 — Laba Rugi' },
  { name: 'laba_rugi_pertumbuhan_yoy_p2', templates: ['muap', 'rsk'], kind: 'fact-display', source: 'app', description: 'laba rugi pertumbuhan yoy p2', anchor: 'MUAP T43 — Laba Rugi' },
  { name: 'laba_rugi_pertumbuhan_yoy_p3', templates: ['muap', 'rsk'], kind: 'fact-display', source: 'app', description: 'laba rugi pertumbuhan yoy p3', anchor: 'MUAP T43 — Laba Rugi' },
  // --- MUAP T45 — Neraca ---
  { name: 'neraca_total_aset_lancar_p1', templates: ['muap', 'rsk'], kind: 'fact-display', source: 'app', description: 'neraca total aset lancar p1', anchor: 'MUAP T45 — Neraca' },
  { name: 'neraca_total_aset_p1', templates: ['muap', 'rsk'], kind: 'fact-display', source: 'app', description: 'neraca total aset p1', anchor: 'MUAP T45 — Neraca' },
  { name: 'neraca_hutang_pendek_p1', templates: ['muap', 'rsk'], kind: 'fact-display', source: 'app', description: 'neraca hutang pendek p1', anchor: 'MUAP T45 — Neraca' },
  { name: 'neraca_total_liabilitas_p1', templates: ['muap', 'rsk'], kind: 'fact-display', source: 'app', description: 'neraca total liabilitas p1', anchor: 'MUAP T45 — Neraca' },
  { name: 'neraca_total_ekuitas_p1', templates: ['muap', 'rsk'], kind: 'fact-display', source: 'app', description: 'neraca total ekuitas p1', anchor: 'MUAP T45 — Neraca' },
  { name: 'neraca_total_aset_lancar_p2', templates: ['muap', 'rsk'], kind: 'fact-display', source: 'app', description: 'neraca total aset lancar p2', anchor: 'MUAP T45 — Neraca' },
  { name: 'neraca_total_aset_p2', templates: ['muap', 'rsk'], kind: 'fact-display', source: 'app', description: 'neraca total aset p2', anchor: 'MUAP T45 — Neraca' },
  { name: 'neraca_hutang_pendek_p2', templates: ['muap', 'rsk'], kind: 'fact-display', source: 'app', description: 'neraca hutang pendek p2', anchor: 'MUAP T45 — Neraca' },
  { name: 'neraca_total_liabilitas_p2', templates: ['muap', 'rsk'], kind: 'fact-display', source: 'app', description: 'neraca total liabilitas p2', anchor: 'MUAP T45 — Neraca' },
  { name: 'neraca_total_ekuitas_p2', templates: ['muap', 'rsk'], kind: 'fact-display', source: 'app', description: 'neraca total ekuitas p2', anchor: 'MUAP T45 — Neraca' },
  { name: 'neraca_total_aset_lancar_p3', templates: ['muap', 'rsk'], kind: 'fact-display', source: 'app', description: 'neraca total aset lancar p3', anchor: 'MUAP T45 — Neraca' },
  { name: 'neraca_total_aset_p3', templates: ['muap', 'rsk'], kind: 'fact-display', source: 'app', description: 'neraca total aset p3', anchor: 'MUAP T45 — Neraca' },
  { name: 'neraca_hutang_pendek_p3', templates: ['muap', 'rsk'], kind: 'fact-display', source: 'app', description: 'neraca hutang pendek p3', anchor: 'MUAP T45 — Neraca' },
  { name: 'neraca_total_liabilitas_p3', templates: ['muap', 'rsk'], kind: 'fact-display', source: 'app', description: 'neraca total liabilitas p3', anchor: 'MUAP T45 — Neraca' },
  { name: 'neraca_total_ekuitas_p3', templates: ['muap', 'rsk'], kind: 'fact-display', source: 'app', description: 'neraca total ekuitas p3', anchor: 'MUAP T45 — Neraca' },
  // --- MUAP T47 — Rasio Keuangan ---
  { name: 'rasio_cr_p1', templates: ['muap', 'rsk'], kind: 'fact-calc', source: 'derived', description: 'rasio cr p1', anchor: 'MUAP T47 — Rasio Keuangan', formula: 'Calculated from related template values at fill time' },
  { name: 'rasio_der_p1', templates: ['muap', 'rsk'], kind: 'fact-calc', source: 'derived', description: 'rasio der p1', anchor: 'MUAP T47 — Rasio Keuangan', formula: 'Calculated from related template values at fill time' },
  { name: 'rasio_dscri_p1', templates: ['muap', 'rsk'], kind: 'fact-calc', source: 'derived', description: 'rasio dscri p1', anchor: 'MUAP T47 — Rasio Keuangan', formula: 'Calculated from related template values at fill time' },
  { name: 'rasio_cr_p2', templates: ['muap', 'rsk'], kind: 'fact-calc', source: 'derived', description: 'rasio cr p2', anchor: 'MUAP T47 — Rasio Keuangan', formula: 'Calculated from related template values at fill time' },
  { name: 'rasio_der_p2', templates: ['muap', 'rsk'], kind: 'fact-calc', source: 'derived', description: 'rasio der p2', anchor: 'MUAP T47 — Rasio Keuangan', formula: 'Calculated from related template values at fill time' },
  { name: 'rasio_dscri_p2', templates: ['muap', 'rsk'], kind: 'fact-calc', source: 'derived', description: 'rasio dscri p2', anchor: 'MUAP T47 — Rasio Keuangan', formula: 'Calculated from related template values at fill time' },
]
