/**
 * Place extraction markers on the master Docs: wrap each field's value with hidden
 * `${{name}}…${{/name}}` sentinels (1pt white) AND create a NamedRange over the
 * value between them. The NamedRange is the SINGLE primitive used for both
 * directions at runtime:
 *   • fill (server/docs/seed.ts)    → `replaceNamedRangeContent` writes the value
 *   • read (server/google/extract)  → text between the sentinels = the value
 *
 * This replaces the old two-script split (ranges for extraction + `{{token}}`
 * literals for fill). The `{{token}}` mechanism is GONE — `setup-template-tokens.ts`
 * is deleted. Re-running this script against a master that still carries old
 * `{{token}}` literals will wrap them with sentinels + create the NamedRange in
 * place; first seed then writes the real content via `replaceNamedRangeContent`.
 *
 * Locators (per anchor):
 *   • structural  — table-cell discovery (RSK risk matrix, MUAP ratio + collateral)
 *   • bracket     — find `[guidance…]` by unique prefix, slice through closing `]`
 *   • exact       — find a unique literal (e.g. "Rp ____________,-")
 *   • token-lit   — find a bare `{{name}}` literal left by the old tokens script
 *   • generic     — scan for hand-authored `${{X}}…${{/X}}` / `${{X}}` already typed
 *
 * Idempotent at the marker-name granularity: a name that already has a NamedRange
 * is skipped, so adding new anchors to a partially-set-up master is safe.
 *
 * COMPLIANCE: anchors never target the RSK risk-matrix LEVELS (`_level` is auto-
 * generated by the matrix locator and lives in extract.ts as a read-only slot;
 * seed.ts' FORBIDDEN_KEY regex is the runtime defence) nor the decision RECOMMENDATION.
 *
 * Run:  pnpm exec tsx apps/web-app/scripts/setup-template-ranges.ts
 */
import { dirname, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'
import { config } from 'dotenv'
import type { docs_v1 } from 'googleapis'
import { docsClient } from '../src/server/google/clients'
import { collectRuns, buildCharMap, findToken, type TextRun } from '../src/server/google/extract/docText'
import { MATRIX_ASPECTS, RATIO_KEYS, type MatrixAspect, type RatioKey } from '../src/lib/extraction/types'
import { sentinelStart, sentinelEnd } from '../src/lib/extraction/anchors'

config({ path: resolve(dirname(fileURLToPath(import.meta.url)), '../.env.local') })

// ── doc helpers ──────────────────────────────────────────────────────────────
function cellRuns(cell: docs_v1.Schema$TableCell): TextRun[] {
  const out: TextRun[] = []
  collectRuns(cell.content ?? undefined, out)
  return out
}
function cellText(cell: docs_v1.Schema$TableCell | undefined): string {
  if (!cell) return ''
  return cellRuns(cell).map((r) => r.text).join('').replace(/\s+/g, ' ').trim()
}
// Index range of a cell's text, excluding the trailing paragraph newline.
function cellBounds(cell: docs_v1.Schema$TableCell | undefined): { start: number; end: number } | null {
  if (!cell) return null
  const runs = cellRuns(cell)
  if (!runs.length) return null
  const start = runs[0].start
  const last = runs[runs.length - 1]
  let end = last.end
  if (last.text.endsWith('\n')) end -= 1
  return { start, end }
}

// Like cellBounds but stops the range before `stopBefore` (e.g. wrap "___%" but
// not the trailing "(min. 80%)" annotation). Trims trailing whitespace.
function valueBounds(cell: docs_v1.Schema$TableCell | undefined, stopBefore?: string): { start: number; end: number } | null {
  if (!cell) return null
  const cm = buildCharMap(cell.content ?? undefined)
  if (!cm.at.length) return null
  let end = cm.full.length
  if (stopBefore) {
    const i = cm.full.indexOf(stopBefore)
    if (i >= 0) end = i
  }
  while (end > 0 && /\s/.test(cm.full[end - 1])) end--
  if (end <= 0) return null
  const start = cm.at[0]
  const endDoc = cm.at[end - 1] + 1
  return endDoc > start ? { start, end: endDoc } : null
}
function tables(doc: docs_v1.Schema$Document): docs_v1.Schema$Table[] {
  return (doc.body?.content ?? []).flatMap((el) => (el.table ? [el.table] : []))
}

// ── structural locators (table-aware) ────────────────────────────────────────
interface Placement { marker: string; start: number; end: number }

const ASPECT_BY_LABEL: Record<string, MatrixAspect> = {
  CHARACTER: 'character',
  CAPACITY: 'capacity',
  CAPITAL: 'capital',
  COLLATERAL: 'collateral',
  CONDITION: 'condition',
  'SHARIA COMPLIANCE': 'sharia_compliance',
  'SHARIA STRUCTURING': 'sharia_structuring',
}

function matrixPlacements(doc: docs_v1.Schema$Document): Placement[] {
  const table = tables(doc).find((t) =>
    (t.tableRows ?? []).some((r) => ASPECT_BY_LABEL[cellText(r.tableCells?.[0]).toUpperCase()]),
  )
  if (!table) return []
  const out: Placement[] = []
  for (const row of table.tableRows ?? []) {
    const cells = row.tableCells ?? []
    const aspect = ASPECT_BY_LABEL[cellText(cells[0]).toUpperCase()]
    if (!aspect) continue
    // cols: 0 Dimensi | 1 Temuan(finding) | 2 Level | 3 Mitigasi
    const map: [string, number][] = [
      [`${aspect}_finding`, 1],
      [`${aspect}_level`, 2],
      [`${aspect}_mitigation`, 3],
    ]
    for (const [marker, col] of map) {
      const b = cellBounds(cells[col])
      if (b) out.push({ marker, ...b })
    }
  }
  return out
}

const RATIO_BY_LABEL: { re: RegExp; key: RatioKey }[] = [
  { re: /current ratio/i, key: 'currentRatio' },
  { re: /debt to equity|\bder\b/i, key: 'der' },
  { re: /gross profit margin|\bgpm\b/i, key: 'gpm' },
  { re: /net profit margin|\bnpm\b/i, key: 'npm' },
  { re: /dscri/i, key: 'dscri' },
]

function ratioPlacements(doc: docs_v1.Schema$Document): Placement[] {
  const table = tables(doc).find(
    (t) =>
      cellText(t.tableRows?.[0]?.tableCells?.[0]).toUpperCase() === 'RASIO' &&
      (t.tableRows?.[0]?.tableCells?.length ?? 0) >= 5,
  )
  if (!table) return []
  const rows = table.tableRows ?? []
  const out: Placement[] = []
  // period headers: row 0, cols 1..3
  const hdr = rows[0]?.tableCells ?? []
  for (const i of [0, 1, 2]) {
    const b = cellBounds(hdr[i + 1])
    if (b) out.push({ marker: `fin_period_${i}`, ...b })
  }
  // ratio rows: cols 1..3 are the period values
  for (const row of rows.slice(1)) {
    const cells = row.tableCells ?? []
    const match = RATIO_BY_LABEL.find((m) => m.re.test(cellText(cells[0])))
    if (!match) continue
    for (const i of [0, 1, 2]) {
      const b = cellBounds(cells[i + 1])
      if (b) out.push({ marker: `ratio_${match.key}_${i}`, ...b })
    }
  }
  return out
}

// MUAP §VII agunan summary: TOTAL row (market value / CEV) + SCCR % row.
function collateralPlacements(doc: docs_v1.Schema$Document): Placement[] {
  const table = tables(doc).find((t) => {
    const r0 = (t.tableRows?.[0]?.tableCells ?? []).map((c) => cellText(c))
    return r0.some((c) => /nilai pasar/i.test(c)) && r0.some((c) => /\bcev\b/i.test(c))
  })
  if (!table) return []
  const rows = table.tableRows ?? []
  const out: Placement[] = []
  const total = rows.find((r) => cellText(r.tableCells?.[1]).toUpperCase() === 'TOTAL')
  if (total) {
    const mv = cellBounds(total.tableCells?.[3])
    if (mv) out.push({ marker: 'collateral_market_value', ...mv })
    const lv = cellBounds(total.tableCells?.[5])
    if (lv) out.push({ marker: 'collateral_liquidation_value', ...lv })
  }
  const sccr = rows.find((r) => /^sccr/i.test(cellText(r.tableCells?.[1])))
  if (sccr) {
    const b = valueBounds(sccr.tableCells?.[5], ' (') // exclude "(min. 80%)"
    if (b) out.push({ marker: 'collateral_sccr_pct', ...b })
  }
  return out
}

// ── text locators (bracket / exact / token-lit) ──────────────────────────────
// Each entry yields a Placement by locating a unique slice of the doc's
// concatenated text. Ordering inside the list matters only for tie-breaking;
// per-name idempotency runs at the placement level.
type TextAnchor =
  | { name: string; kind: 'bracket'; prefix: string }      // [guidance…] by unique prefix
  | { name: string; kind: 'exact'; text: string }          // unique literal in the doc
  | { name: string; kind: 'token-lit' }                    // legacy {{name}} from old tokens script

const MUAP_TEXT_ANCHORS: TextAnchor[] = [
  // Header fields
  { name: 'f_nasabah', kind: 'bracket', prefix: '[Nama Nasabah]' },
  { name: 'f_akad', kind: 'bracket', prefix: '[Murabahah / Musyarakah / Ijarah / IMBT / Istishna / Salam]' },
  { name: 'f_tujuan', kind: 'bracket', prefix: '[Deskripsi tujuan penggunaan pembiayaan yang dimohon nasabah]' },
  { name: 'f_plafond', kind: 'exact', text: 'Rp ____________,- ([Terbilang])' },
  { name: 'f_tenor', kind: 'exact', text: '___ Bulan' },
  // 5C+1S narrative slots
  { name: 'm_ringkasan_usulan', kind: 'bracket', prefix: '[Jelaskan kondisi fasilitas existing di bank ini,' },
  { name: 'm_tujuan_naratif', kind: 'bracket', prefix: '[Jelaskan kebutuhan pembiayaan nasabah secara naratif:' },
  { name: 'm_capacity', kind: 'bracket', prefix: '[Berikan narasi analisis tren:' },
  { name: 'm_capital', kind: 'bracket', prefix: '[Analisis kunci neraca:' },
  { name: 'm_condition', kind: 'bracket', prefix: '[Uraikan industri di mana nasabah beroperasi:' },
  { name: 'm_collateral', kind: 'bracket', prefix: '[Tuliskan: (1) status kepemilikan agunan' },
  { name: 'm_syariah', kind: 'bracket', prefix: '[Tuliskan opini syariah secara naratif:' },
]
// MUAP `m_character` has no clean bracket prefix on the master — DEFERRED. Same
// for DSR/LTV/Kol + income/obligations/installment (no clean field in the master).

const RSK_TEXT_ANCHORS: TextAnchor[] = [
  { name: 'f_nasabah', kind: 'bracket', prefix: '[Nama Perusahaan / Individu]' },
  { name: 'f_akad', kind: 'bracket', prefix: '[Musyarakah / Murabahah / Ijarah / Istishna / dll.]' },
  { name: 'f_tenor', kind: 'exact', text: '[X] bulan sejak penandatanganan akad' },
  // RSK risk prose (per aspect) is wired through the matrix locator above —
  // the matrix already creates `<asp>_finding` / `<asp>_mitigation` NamedRanges
  // around the matrix cells. No extra anchors needed for risk prose.
  // f_plafond is intentionally absent: positionally fragile on the RSK template.
]

// Locate every TextAnchor that doesn't yet have a NamedRange. Falls back to
// the legacy `{{name}}` literal if the original locator doesn't match — this
// is the migration path for masters that already went through the old tokens
// script (the bracket / exact source string is already gone, replaced by `{{name}}`).
function textPlacements(doc: docs_v1.Schema$Document, anchors: TextAnchor[]): Placement[] {
  const cm = buildCharMap(doc.body?.content ?? undefined)
  const existing = new Set(Object.keys(doc.namedRanges ?? {}))
  const out: Placement[] = []
  for (const a of anchors) {
    if (existing.has(a.name)) continue
    // 1. Legacy token literal — wins if present (the master was already tokenized once).
    const litIdx = cm.full.indexOf(`{{${a.name}}}`)
    if (litIdx >= 0) {
      const start = cm.at[litIdx]
      const end = cm.at[litIdx + `{{${a.name}}}`.length - 1] + 1
      out.push({ marker: a.name, start, end })
      continue
    }
    // 2. Original locator (bracket / exact).
    if (a.kind === 'bracket') {
      const i = cm.full.indexOf(a.prefix)
      if (i < 0) continue
      const close = cm.full.indexOf(']', i + a.prefix.length - 1)
      if (close < 0) continue
      const start = cm.at[i]
      const end = cm.at[close] + 1
      out.push({ marker: a.name, start, end })
    } else if (a.kind === 'exact') {
      const i = cm.full.indexOf(a.text)
      if (i < 0) continue
      const start = cm.at[i]
      const end = cm.at[i + a.text.length - 1] + 1
      out.push({ marker: a.name, start, end })
    }
    // 'token-lit' branch is handled above unconditionally — kept in the type for
    // explicitness; no separate case needed.
  }
  return out
}

// ── two-pass placement ───────────────────────────────────────────────────────
const WHITE = { color: { rgbColor: { red: 1, green: 1, blue: 1 } } }
const HIDDEN = { foregroundColor: WHITE, fontSize: { magnitude: 1, unit: 'PT' } }

async function setupDoc(
  docs: docs_v1.Docs,
  documentId: string,
  label: string,
  placements: Placement[],
): Promise<void> {
  const before = await docs.documents.get({ documentId })
  const cm0 = buildCharMap(before.data.body?.content ?? undefined)

  if (placements.length === 0) {
    console.log(`\n[${label}] ⚠ no fields located — check template structure.`)
    return
  }
  // Per-marker idempotency: only place markers not already present.
  const todo = placements.filter((p) => !findToken(cm0, sentinelStart(p.marker)))
  if (todo.length === 0) {
    console.log(`\n[${label}] all ${placements.length} markers already present — skipping.`)
    return
  }

  // Pass 1: insert ${{name}} … ${{/name}} tokens around each value. Empty cell →
  // one combined token with a "-" placeholder so a NamedRange can exist.
  const inserts: { index: number; text: string }[] = []
  for (const p of todo) {
    if (p.end > p.start) {
      inserts.push({ index: p.end, text: ` ${sentinelEnd(p.marker)}` })
      inserts.push({ index: p.start, text: `${sentinelStart(p.marker)} ` })
    } else {
      inserts.push({ index: p.start, text: `${sentinelStart(p.marker)} - ${sentinelEnd(p.marker)}` })
    }
  }
  inserts.sort((a, b) => b.index - a.index) // descending: lower indices stay valid
  await docs.documents.batchUpdate({
    documentId,
    requestBody: { requests: inserts.map((i) => ({ insertText: { location: { index: i.index }, text: i.text } })) },
  })

  // Pass 2: locate tokens by text, create NamedRanges + hide the token spans.
  const after = await docs.documents.get({ documentId })
  const cm = buildCharMap(after.data.body?.content ?? undefined)
  const requests: docs_v1.Schema$Request[] = []
  let placed = 0
  const failed: string[] = []
  for (const p of todo) {
    const s = findToken(cm, sentinelStart(p.marker))
    const e = s ? findToken(cm, sentinelEnd(p.marker), s.offset + sentinelStart(p.marker).length) : null
    if (!s || !e) {
      failed.push(p.marker)
      continue
    }
    if (e.start > s.end) {
      requests.push({ createNamedRange: { name: p.marker, range: { startIndex: s.end, endIndex: e.start } } })
    }
    requests.push({ updateTextStyle: { range: { startIndex: s.start, endIndex: s.end }, textStyle: HIDDEN, fields: 'foregroundColor,fontSize' } })
    requests.push({ updateTextStyle: { range: { startIndex: e.start, endIndex: e.end }, textStyle: HIDDEN, fields: 'foregroundColor,fontSize' } })
    placed++
  }
  await docs.documents.batchUpdate({ documentId, requestBody: { requests } })
  console.log(`\n[${label}] placed ${placed}/${todo.length} new markers (of ${placements.length} total).`)
  if (failed.length) console.log(`  ✗ failed: ${failed.join(', ')}`)
}

// Pass B: pick up any hand-authored tokens not covered by structural/text anchors.
// Paired `${{X}} … ${{/X}}` → NamedRange over the content (tokens hidden).
// Lone `${{X}}` → NamedRange over the token itself (kept visible; analyst replaces it).
async function scanHandAuthoredTokens(docs: docs_v1.Docs, documentId: string, label: string): Promise<void> {
  const doc = (await docs.documents.get({ documentId })).data
  const cm = buildCharMap(doc.body?.content ?? undefined)
  const existing = new Set(Object.keys(doc.namedRanges ?? {}))

  const re = /\$\{\{(\/?)(\w+)\}\}/g
  const toks: { kind: 'open' | 'close'; name: string; start: number; end: number }[] = []
  for (let m = re.exec(cm.full); m; m = re.exec(cm.full)) {
    const name = m[2]
    if (!name) continue
    toks.push({ kind: m[1] ? 'close' : 'open', name, start: cm.at[m.index], end: cm.at[m.index + m[0].length - 1] + 1 })
  }

  const requests: docs_v1.Schema$Request[] = []
  const created: string[] = []
  const usedClose = new Set<number>()
  const hide = (s: number, e: number): docs_v1.Schema$Request => ({
    updateTextStyle: { range: { startIndex: s, endIndex: e }, textStyle: HIDDEN, fields: 'foregroundColor,fontSize' },
  })
  toks.forEach((t, i) => {
    if (t.kind !== 'open' || existing.has(t.name)) return
    let close: (typeof toks)[number] | undefined
    for (let j = i + 1; j < toks.length; j++) {
      if (toks[j].kind === 'close' && toks[j].name === t.name && !usedClose.has(j)) {
        close = toks[j]
        usedClose.add(j)
        break
      }
    }
    if (close && close.start > t.end) {
      requests.push({ createNamedRange: { name: t.name, range: { startIndex: t.end, endIndex: close.start } } })
      requests.push(hide(t.start, t.end), hide(close.start, close.end))
    } else {
      requests.push({ createNamedRange: { name: t.name, range: { startIndex: t.start, endIndex: t.end } } })
    }
    created.push(t.name)
    existing.add(t.name)
  })

  if (requests.length) await docs.documents.batchUpdate({ documentId, requestBody: { requests } })
  if (created.length) console.log(`[${label}] generic scan: created ${created.length} hand-authored marker(s): ${created.join(', ')}`)
}

async function main() {
  const docs = docsClient()
  const rsk = process.env.GOOGLE_MASTER_RSK_DOC_ID
  const muap = process.env.GOOGLE_MASTER_MUAP_DOC_ID
  if (!rsk || !muap) throw new Error('Missing GOOGLE_MASTER_{RSK,MUAP}_DOC_ID — run create-masters first.')

  const rskDoc = (await docs.documents.get({ documentId: rsk })).data
  await setupDoc(docs, rsk, 'RSK matrix', matrixPlacements(rskDoc))
  // Re-fetch — structural pass mutated the doc, indices have moved.
  const rskAfterMatrix = (await docs.documents.get({ documentId: rsk })).data
  await setupDoc(docs, rsk, 'RSK text fields', textPlacements(rskAfterMatrix, RSK_TEXT_ANCHORS))
  await scanHandAuthoredTokens(docs, rsk, 'RSK')

  const muapDoc = (await docs.documents.get({ documentId: muap })).data
  await setupDoc(docs, muap, 'MUAP ratios + collateral', [...ratioPlacements(muapDoc), ...collateralPlacements(muapDoc)])
  const muapAfterStructural = (await docs.documents.get({ documentId: muap })).data
  await setupDoc(docs, muap, 'MUAP text fields', textPlacements(muapAfterStructural, MUAP_TEXT_ANCHORS))
  await scanHandAuthoredTokens(docs, muap, 'MUAP')

  console.log(`\nExpected — matrix: ${MATRIX_ASPECTS.length * 3}, ratios: ${RATIO_KEYS.length * 3} + 3 periods, collateral: 3, MUAP text: ${MUAP_TEXT_ANCHORS.length}, RSK text: ${RSK_TEXT_ANCHORS.length}.`)
}

main().catch((e) => {
  console.error(e)
  process.exit(1)
})
