'use server'

import { requireActor } from '@/server/auth/session'
import { stageOwnerResolver } from '@/server/auth/stage-owners'
import { AuthzError, auditUserName } from '@/lib/auth/can'
import { loadApplicationForWrite, saveApplication } from '@/server/repo/write'
import { appendApprovalStep, loadApprovalSteps } from '@/server/repo/approval'
import { isChainComplete, validateAction, currentCycleSteps, type ApprovalAction, type ApprovalChain } from '@/lib/approval-chain'
import { approvalRoleForActor } from '@/lib/approval-desks'
import { routingAllowsActor } from '@/lib/approval-routing'
import { getActiveApprovalRouting } from '@/server/config/approval-routing'
import type { LoanApplication } from '@/lib/types'
import { CHAIN_COMPLETE_ADVANCE, makerSubmitGateError } from '@/lib/stage-action'
import { dispatch } from '@/lib/workflow-engine'
import { stampSignatureQr } from '@/server/docs/qr-stamp'
import { reconcileFrozenDocGrants } from '@/server/docs/access'
import { ensureStage4DocsOnEntry } from '@/server/docs/auto-draft'
import { SIG_SLOT_OF_APPROVAL_ROLE } from '@/lib/approval-desks'
import { getDocLinkage } from '@/server/repo/doc-linkage'
import { log, errField } from '@/server/log'
import { snapshotApplicationDocs, finalizeSignedDoc } from '@/server/docs/service'

// Maker-checker ladder actions (MUAP: RM→TL · RSK: RA→RTL — two-rung chains, ADR-0021). Identity is read
// from the verified session (requireActor) — NEVER the client. Both gates run server-side before
// any ledger write because these are POST-reachable: the DESK gate (approvalRoleForActor — does
// the actor hold the rung the chain awaits?) and the pure RULE gate (validateAction — order +
// four-eyes). The append is version-guarded. The ladder rules live in lib/approval-chain.ts.

const CHAIN_LABEL: Record<ApprovalChain, string> = { muap: 'MUAP', rsk: 'RSK', sp3: 'SP3' }
// 'reset' never flows through actOnChain (it is appended by the revise path with its own audit
// text) — listed only to keep the map exhaustive over ApprovalAction.
const ACTION_VERB: Record<ApprovalAction, string> = { request: 'Ajukan', approve: 'Setujui', reject: 'Kembalikan', reset: 'Batalkan' }

async function snapshotDocsBestEffort(appId: string, actor: Awaited<ReturnType<typeof requireActor>>, label: string): Promise<void> {
  try {
    await snapshotApplicationDocs(appId, { trigger: 'stage_transition', label, createdBy: actor.userId, createdByName: auditUserName(actor) })
  } catch (e) {
    log.warn('docs.snapshot_skipped', { appId, trigger: 'stage_transition', ...errField(e) })
  }
}

async function actOnChain(
  appId: string,
  chain: ApprovalChain,
  action: ApprovalAction,
  reason: string | undefined,
): Promise<LoanApplication> {
  const actor = await requireActor()
  const app = await loadApplicationForWrite(appId)
  if (!app) throw new Error(`Application ${appId} not found`)

  // Maker submit-to-checker gate (Batch 3 T5): the deliverable that must exist before opening the
  // ladder — MUAP↔Legal+Appraisal (ADR-0007), RSK↔the recorded risk recommendation (closes #14, and
  // with the single ladder-only 4→5 path stops a signed-first deal reaching Komite without a
  // recommendation, #13). Single source of truth: makerSubmitGateError.
  if (action === 'request') {
    const gateErr = makerSubmitGateError(chain, app)
    if (gateErr) throw new AuthzError(gateErr)
  }

  // N2 (ADR-0018): the MUAP is now minted by an explicit RM "Generate MUAP", so it can be absent. You
  // cannot ladder-approve a memo that doesn't exist — block the MUAP request until the doc is minted.
  // (makerSubmitGateError is a pure fn over the app and can't see DocLinkage; this is the clean site —
  // actOnChain already reads DocLinkage below for the QR stamp.) Original already-minted flows: no-op.
  if (action === 'request' && chain === 'muap') {
    const linkage = await getDocLinkage(appId)
    if (!linkage?.muapDocId) throw new AuthzError('Buat (Generate) MUAP dulu sebelum diajukan ke Risk.')
  }

  // N1 (rm-led-pipeline-redesign §4): the SP3 Legal-review chain can only open once the SP3 offer
  // letter exists (mirrors the MUAP doc-existence gate). Generated by generateSp3Action →
  // DocLinkage.sp3DocId; drafting opens at decision-recorded. You cannot ladder-review a missing doc.
  if (action === 'request' && chain === 'sp3') {
    const linkage = await getDocLinkage(appId)
    if (!linkage?.sp3DocId) throw new AuthzError('Buat (Generate) SP3 dulu sebelum diajukan ke review Legal.')
  }

  // Hard-gate (DSR/LTV/Kol) additionally blocks the MUAP approval REQUEST. Override is self-service:
  // the `reason` doubles as the override reason and is recorded on the ledger — no separate approval.
  if (action === 'request' && chain === 'muap') {
    const violations = app.hardGateViolations ?? []
    if (violations.length && !reason) {
      throw new AuthzError(
        `Hard-gate terlampaui (${violations.join(', ').toUpperCase()}). Beri alasan override untuk tetap mengajukan.`,
      )
    }
  }

  const ledger = await loadApprovalSteps(appId, chain)
  const role = approvalRoleForActor(chain, action, ledger, actor.desks)
  if (!role) throw new AuthzError('Anda tidak memegang desk yang berwenang untuk aksi ini sekarang.')

  const check = validateAction(chain, ledger, { role, action, userId: actor.userId })
  if (!check.ok) throw new AuthzError(check.reason)

  // STRICT per-submitter routing (approval-routing-config.md): when the maker has a rule designating
  // an account for THIS rung, only that account may sign it — other desk holders are narrowed out
  // (unconfigured rung → fallback to all holders; superadmin keeps break-glass, ADR-0010). The desk
  // gate + validateAction above remain the authority/order/four-eyes backstops; routing only RESTRICTS.
  if (action === 'approve' || action === 'reject') {
    const makerId = currentCycleSteps(chain, ledger)[0]?.userId
    if (makerId) {
      const routing = await getActiveApprovalRouting(makerId, chain)
      if (!routingAllowsActor(routing, role, actor.userId, actor.isSuperadmin)) {
        throw new AuthzError('Persetujuan rung ini telah dirutekan ke akun lain. Hubungi admin bila rute perlu diubah.')
      }
    }
  }

  const updated = await appendApprovalStep({
    appId,
    expectedVersion: app.version ?? 0,
    chain,
    role,
    action,
    userId: actor.userId,
    userName: auditUserName(actor),
    reason,
    audit: { action: `${ACTION_VERB[action]} ${CHAIN_LABEL[chain]} (${role})`, stage: app.stage },
  })

  // Best-effort: stamp the signature QR into the per-app Doc at this rung's signature slot. The
  // ledger + /qr/<token> verify page are authoritative; the in-Doc stamp is a printed-artifact
  // convenience, so a failure here (no Doc yet, render API down, slot absent) NEVER blocks approval.
  //
  // Stamp on every SIGNATURE action: the maker's `request` (slot `tanggal_ttd_rm`/`rsk_sig_analyst_tanggal`)
  // AND the checker `approve` rungs — both mint a qrToken in appendApprovalStep. `reject` is not a
  // signature (no token), so it falls through. One slot per `role` via SIG_SLOT_OF_APPROVAL_ROLE closes
  // both chains. (Batch 2 — fixes the gap where the maker's slot stayed empty in the final document.)
  if (action === 'approve' || action === 'request') {
    const minted = (updated.approvalSteps ?? [])
      .filter((s) => s.chain === chain && s.role === role && s.action === action)
      .at(-1)?.qrToken
    if (minted) {
      try {
        const linkage = await getDocLinkage(appId)
        const docId = chain === 'muap' ? linkage?.muapDocId : chain === 'sp3' ? linkage?.sp3DocId : linkage?.rskDocId
        if (docId) {
          await stampSignatureQr({
            documentId: docId,
            namedRangeName: SIG_SLOT_OF_APPROVAL_ROLE[role],
            token: minted,
            baseUrl: process.env.APP_BASE_URL ?? 'https://mizan.hijra.id',
          })
        }
      } catch (e) {
        log.error('approval.qr_stamp_failed', { appId, chain, role, ...errField(e) })
      }
    }
  }

  // The ladder IS the advance gate: when this approval completes the chain, a FINAL MUAP/RSK
  // carries the application forward (replacing the old manual LA/RT transition). Done as a second
  // version-guarded write so the approval and the advance stay distinct, ordered audit events.
  // CARDINAL CONSTRAINT (N1): the SP3 chain is NOT a stage gate — its completion is a disbursement
  // PREREQUISITE only (gated at advanceDisbursementAction via sp3FinalReady). So sp3 has no
  // CHAIN_COMPLETE_ADVANCE row and must NEVER fire a SystemTransition; only muap/rsk advance here.
  if (action === 'approve' && chain !== 'sp3') {
    const ledgerAfter = await loadApprovalSteps(appId, chain)
    const advance = CHAIN_COMPLETE_ADVANCE[chain]
    if (isChainComplete(chain, ledgerAfter) && updated.stage === advance.from) {
      const fresh = await loadApplicationForWrite(appId)
      if (fresh) {
        dispatch(fresh, { kind: 'SystemTransition', transition: advance.config }, actor, undefined, await stageOwnerResolver())
        const saved = await saveApplication(fresh)
        await snapshotDocsBestEffort(appId, actor, `${CHAIN_LABEL[chain]} selesai → Tahap ${saved.stage}`)
        // Batch 3 T2: the doc just FROZE on this advance (MUAP 3→4 / RSK 4→5) — downgrade any
        // lingering Drive `writer` grants to reader so a beku doc isn't still editable (audit hole).
        const linkage = await getDocLinkage(appId)
        if (linkage) await reconcileFrozenDocGrants(saved, linkage)
        // Batch 4 V3.5: the ladder is now COMPLETE → the doc is official. Re-fill its date/number slots
        // (No. MUAP, Tanggal, [Tanggal MUAP]) with the last signature's date. Best-effort (never throws).
        await finalizeSignedDoc(appId, chain, actor.userId)
        // Batch 3 T3: entering Stage 4 (MUAP ladder complete) is where the RSK is born, grounded in
        // the now-final MUAP (read-back + create). Fire-after-advance, best-effort (never throws).
        await ensureStage4DocsOnEntry(saved, advance.from, actor.userId)
        return saved
      }
    }
  }
  return updated
}

/**
 * The maker requests checker approval on a document chain (opens / re-opens the ladder). For
 * MUAP, hard-gate violations block this unless `overrideReason` is supplied (self-service).
 */
export async function requestApprovalAction(
  appId: string,
  chain: ApprovalChain,
  overrideReason?: string,
): Promise<LoanApplication> {
  return actOnChain(appId, chain, 'request', overrideReason?.trim() || undefined)
}

/** The current checker rung approves; the last approve completes the chain (freeze wires in next). */
export async function approveStepAction(appId: string, chain: ApprovalChain): Promise<LoanApplication> {
  return actOnChain(appId, chain, 'approve', undefined)
}

/** The current checker rung sends the document back to the maker; the reason is mandatory. */
export async function rejectStepAction(
  appId: string,
  chain: ApprovalChain,
  reason: string,
): Promise<LoanApplication> {
  if (!reason?.trim()) throw new AuthzError('Alasan wajib diisi saat mengembalikan dokumen.')
  return actOnChain(appId, chain, 'reject', reason.trim())
}
